// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 OnPrem AI Gateway contributors

// Code generated by interfacer; DO NOT EDIT

package portal

import (
	"context"
	"encoding/json"
	"op-ai-gateway/internal/auth"
	"op-ai-gateway/internal/netbird"
	"op-ai-gateway/internal/routing"
	"op-ai-gateway/internal/usage"
	"time"
)

// API is an interface generated for "op-ai-gateway/internal/portal.Service".
type API interface {
	ActiveAgentPresenceTimeoutSeconds(context.Context) int
	AddGroupMembers(context.Context, auth.Token, string, []string) error
	AddProjectGroups(context.Context, auth.Token, string, []string) error
	AddProjectMembers(context.Context, auth.Token, string, []string) error
	AddServerToResourceGroup(context.Context, auth.Token, string, string) error
	AddUserToAdminGroup(context.Context, auth.Token, string, string, string) error
	AdminOwnerCandidates(context.Context, auth.Token) ([]AdminOwnerCandidateDTO, error)
	AgentTokenStatus(context.Context, auth.Token, string) (AgentTokenDTO, error)
	AgentCertificate(context.Context, string) (AgentCertificateDTO, error)
	AgentProxyRoutes(context.Context, string) (AgentProxyRoutesDTO, error)
	AgentRuntimeConfig(context.Context, string) (AgentRuntimeConfigDTO, error)
	AllowedServerIDs(context.Context, auth.Token, []string) (map[string]bool, error)
	AuthorizeBenchmarkScope(context.Context, auth.Token, string, string) (routing.AIServer, []BenchmarkTargetView, error)
	AuthorizeRunAsToken(context.Context, auth.Token, string) (auth.Token, error)
	AuthorizeServerManage(context.Context, auth.Token, string) error
	CaptureDetail(auth.Token, string) (CaptureDetail, error)
	CertEdgeRequireHTTPSChecked(context.Context) bool
	CertMeshRequireTLSChecked(context.Context) bool
	CertMeshTLSSeparateActive(context.Context) (bool, error)
	CertModuleChecked(context.Context) bool
	CertificateCABundlePEM(context.Context) (string, error)
	CertificateCAView(context.Context) (CertificateCADTO, error)
	CertificatesView(context.Context) ([]CertificateDTO, error)
	CheckpointAssistant(context.Context, auth.Token, string, AssistantTurn) error
	CommitAssistant(context.Context, auth.Token, string, AssistantTurn, string) error
	CreateApplication(context.Context, auth.Token, string, CreateApplicationRequest) (ApplicationDTO, error)
	CreateChat(context.Context, auth.Token, CreateChatRequest) (ChatDTO, error)
	CreateGatewaySetupKey(context.Context, auth.Token) (string, string, error)
	CreateGroup(context.Context, auth.Token, CreateGroupInput) (UserGroupDTO, error)
	CreateMapping(context.Context, auth.Token, string, CreateMappingRequest) (ModelMappingDTO, error)
	CreateModelGroup(context.Context, auth.Token, CreateModelGroupRequest) (ModelGroupDTO, error)
	CreateProject(context.Context, auth.Token, CreateProjectInput) (ProjectDTO, error)
	CreateResourceGroup(context.Context, auth.Token, CreateResourceGroupRequest) (ResourceGroupDTO, error)
	CreateServer(context.Context, auth.Token, CreateServerRequest) (ServerDTO, error)
	CreateService(context.Context, auth.Token, CreateServiceRequest) (ServiceDTO, error)
	CreateServiceToken(context.Context, auth.Token, string, CreateServiceTokenRequest) (CreateServiceTokenResponse, error)
	CreateToken(context.Context, auth.Token, CreateTokenRequest) (CreateTokenResponse, error)
	CurrencyUsdPerEur(context.Context) float64
	CurrentUser(context.Context, auth.Token) (CurrentUser, error)
	Dashboard(context.Context, auth.Token) DashboardResponse
	DeleteApplication(context.Context, auth.Token, string) error
	DeleteCapture(auth.Token, string) error
	DeleteChat(context.Context, auth.Token, string) error
	DeleteGroup(context.Context, auth.Token, string) error
	DeleteMapping(context.Context, auth.Token, string) error
	DeleteModelGroup(context.Context, auth.Token, string) error
	DeleteProject(context.Context, auth.Token, string) error
	DeleteResourceGroup(context.Context, auth.Token, string) error
	DeleteRuntimeSpec(context.Context, auth.Token, string) error
	DeleteServer(context.Context, auth.Token, string, bool) (bool, error)
	DeleteService(context.Context, auth.Token, string) error
	DeleteServiceToken(context.Context, auth.Token, string, string) error
	DeleteToken(context.Context, auth.Token, string) error
	DemoteManager(context.Context, auth.Token, string, string) error
	DetachProjectToken(context.Context, auth.Token, string, string) error
	DisplayNames(context.Context, []string) map[string]string
	EdgeCertificateBundlePEM(context.Context) (string, error)
	EdgeCertificateKeyPEM(context.Context) (string, error)
	EdgeCertificateView(context.Context) (EdgeCertificateDTO, error)
	EdgeProxyConfig(context.Context) (string, error)
	EnrollGatewaySidecar(context.Context, auth.Token) (string, string, error)
	ExternalThemeAsset(string, string) (string, bool)
	GenerateAgentToken(context.Context, auth.Token, string) (GenerateAgentTokenResponse, error)
	GatewayCARotationPendingServers(context.Context) []CertificateServerRefDTO
	MeshTLSPendingServers(context.Context) []CertificateServerRefDTO
	HTTPSSwitchUnreachableApps(context.Context) []HTTPSSwitchUnreachableDTO
	PublicCertificateBundlePEM(context.Context, string) (string, error)
	PublicCertificateKeyPEM(context.Context, string) (string, error)
	GatewayMeshCertificate(context.Context) (GatewayMeshCertificateMaterial, error)
	GetApplication(context.Context, auth.Token, string) (ApplicationDTO, error)
	GetChat(context.Context, auth.Token, string) (ChatDTO, error)
	GetCoResidency(context.Context, auth.Token, string) (CoResidencyDTO, error)
	GetModelGroup(context.Context, auth.Token, string) (ModelGroupDTO, error)
	GetResourceGroup(context.Context, auth.Token, string) (ResourceGroupDTO, error)
	GetRuntimeSpec(context.Context, auth.Token, string) (RuntimeSpecDTO, error)
	GetServer(context.Context, auth.Token, string) (ServerDTO, error)
	GetServerGPUBudgets(context.Context, auth.Token, string) ([]GPUBudgetDTO, error)
	GetService(context.Context, auth.Token, string) (ServiceDTO, error)
	GroupMemberCandidates(context.Context, auth.Token, string) ([]UserRefDTO, error)
	GroupMembers(context.Context, auth.Token, string) ([]UserGroupMemberDTO, error)
	HealthCheckIntervalSeconds(context.Context) int
	ListApplications(context.Context, auth.Token, string) (ApplicationListResponse, error)
	ListChats(context.Context, auth.Token) ([]ChatSummaryDTO, error)
	ListGroups(context.Context, auth.Token) (GroupLandscapeDTO, error)
	ListInvitations(context.Context, auth.Token) ([]InvitationDTO, error)
	ListMappings(context.Context, auth.Token, string) (MappingListResponse, error)
	ListModelGroups(context.Context, auth.Token) (ModelGroupsResponse, error)
	ListProjects(context.Context, auth.Token) ([]ProjectDTO, error)
	ListResourceGroups(context.Context, auth.Token) ([]ResourceGroupDTO, error)
	ListServers(context.Context, auth.Token) (ServerListResponse, error)
	ListServiceTokens(context.Context, auth.Token, string) ([]ServiceTokenDTO, error)
	ListServices(context.Context, auth.Token) ([]ServiceDTO, error)
	ListTokens(context.Context, auth.Token) (TokenListResponse, error)
	ManageableUserIDs(context.Context, auth.Token) (map[string]bool, error)
	ManageModels(context.Context, auth.Token) ModelsResponse
	MappingBenchmarks(context.Context, auth.Token, string, int) ([]BenchmarkRunDTO, error)
	ModelOfferingFor(context.Context, auth.Token, string) ModelOffering
	ModelServers(context.Context, auth.Token, string) ([]ModelServerDTO, error)
	Models(context.Context, auth.Token) ModelsResponse
	ModelsForFlavor(context.Context, auth.Token, string) []string
	MyProjects(context.Context, auth.Token) ([]ProjectRefDTO, error)
	NetbirdAgentDownloadOnly(context.Context) bool
	NetbirdConfig(context.Context) (NetbirdConfig, bool, error)
	NetbirdGatewayPeerID(context.Context) string
	NetbirdGroups(context.Context) ([]netbird.Group, error)
	NetbirdKeyFileConfigured() bool
	NetbirdModuleChecked(context.Context) bool
	NetbirdModuleEnabled(context.Context) bool
	NetbirdNetwork(context.Context) (NetbirdNetworkDTO, error)
	NetbirdOnly(context.Context) bool
	NetbirdPeers(context.Context) ([]netbird.Peer, error)
	NetbirdPolicyContext(context.Context) NetbirdPolicyContextDTO
	NetbirdTokenStatus(context.Context) (NetbirdTokenStatusDTO, error)
	PrepareChatRun(context.Context, auth.Token, string, PrepareRunRequest) ([]ChatAPIMessage, ChatRunSettings, error)
	ProbeEdgeTLS(context.Context) (EdgeProbeDTO, error)
	ProjectCandidates(context.Context, auth.Token, string) ([]UserRefDTO, []GroupRefDTO, error)
	ProjectMembersView(context.Context, auth.Token, string) (ProjectMembersDTO, error)
	ProjectTokens(context.Context, auth.Token, string) (ProjectTokensView, error)
	PromoteManager(context.Context, auth.Token, string, string, bool, bool, bool, bool, bool) error
	PublicLanguage(context.Context) string
	PublicTheme(context.Context) string
	PublicThemeView(context.Context) ThemePublicView
	PutRuntimeSpec(context.Context, auth.Token, string, PutRuntimeSpecRequest) (RuntimeSpecDTO, error)
	ReassignGroupsOwnedBy(context.Context, auth.Token, string) error
	ReconcileCertificates(context.Context)
	ReconcileGatewayPeer(context.Context) (string, bool, error)
	RegenerateNetbirdKey(context.Context, auth.Token, string) (string, string, error)
	ReissueAllCertificates(context.Context, auth.Token) error
	ReissueEdgeCertificate(context.Context, auth.Token) error
	RemoveGroupMember(context.Context, auth.Token, string, string) error
	RemoveProjectGroup(context.Context, auth.Token, string, string) error
	RemoveProjectMember(context.Context, auth.Token, string, string) error
	RemoveServerFromResourceGroup(context.Context, auth.Token, string, string) error
	RenameGroup(context.Context, auth.Token, string, string) (UserGroupDTO, error)
	RenewCertificateNow(context.Context, auth.Token, string) error
	ResolveGatewayPeerDNS(context.Context) (string, error)
	ResolveGatewayPeerIP(context.Context) (string, error)
	ResolveInviteAdminGroup(context.Context, auth.Token, string) (string, string, error)
	ResourceGroupAdminGroupCandidates(context.Context, auth.Token) ([]AdminGroupCandidateDTO, error)
	ResourceGroupProvisionCandidates(context.Context, auth.Token, string) (ResourceGroupProvisionCandidatesDTO, error)
	ResourceGroupProvisionsView(context.Context, auth.Token, string) ([]ResourceGroupProvisionDTO, error)
	ResourceGroupServerCandidates(context.Context, auth.Token, string) ([]ResourceGroupServerRefDTO, error)
	RespondInvitation(context.Context, auth.Token, string, bool) error
	RevokeAgentToken(context.Context, auth.Token, string) error
	RotateCertificateCA(context.Context, auth.Token) error
	RotateNetbirdToken(context.Context, auth.Token) (RotateNetbirdTokenResult, error)
	RotateServiceToken(context.Context, auth.Token, string, string) (CreateServiceTokenResponse, error)
	RotateToken(context.Context, auth.Token, string) (CreateTokenResponse, error)
	RuntimeWarnings(context.Context, auth.Token, string) ([]string, error)
	SMTPRuntimeConfig(context.Context) (SMTPRuntimeConfig, error)
	SaveChat(context.Context, auth.Token, string, UpdateChatRequest) (ChatDTO, error)
	ServerAdminGroupCandidates(context.Context, auth.Token) ([]AdminGroupCandidateDTO, error)
	ServerAvailability(context.Context, auth.Token, string, time.Duration) ([]routing.ServerAvailabilitySample, error)
	ServerHardware(context.Context, auth.Token, string) (routing.ServerHardware, bool, error)
	ServerModels(context.Context, auth.Token, string) ([]ServerModelDTO, error)
	ServerOwnerResourceGroups(context.Context, auth.Token, string) ([]ServerResourceGroupDTO, error)
	ServerPerfHistory(context.Context, auth.Token, string, time.Duration) ([]routing.TelemetrySample, error)
	ServerRuntimeReportView(context.Context, auth.Token, string) (ServerRuntimeReportViewDTO, error)
	ServiceAdminGroupCandidates(context.Context, auth.Token) ([]AdminGroupCandidateDTO, error)
	SetBenchmarkRuntimeSpecAdminState(context.Context, string, string, string) (RuntimeSpecDTO, error)
	SetCaptureSecret(auth.Token, string, bool) error
	SetCoResidency(context.Context, auth.Token, string, SetCoResidencyRequest) (CoResidencyDTO, error)
	SetManagerPermissions(context.Context, auth.Token, string, string, bool, bool, bool, bool, bool) error
	SetModelVisibility(context.Context, auth.Token, string, string) error
	SetNetbirdNetwork(context.Context, auth.Token, NetbirdNetworkDTO) (NetbirdNetworkDTO, error)
	SetResourceGroupAdminGroups(context.Context, auth.Token, string, []string) (ResourceGroupDTO, error)
	SetResourceGroupProvisions(context.Context, auth.Token, string, []routing.ResourceGroupProvision) error
	SetResourceGroupServers(context.Context, auth.Token, string, []string) (ResourceGroupDTO, error)
	SetServerAdminGroups(context.Context, auth.Token, string, []string) (ServerDTO, error)
	SetServerCertificateOverride(context.Context, auth.Token, string, string) (ServerDTO, error)
	SetServerEnergyConfig(context.Context, auth.Token, string, float64, float64, float64, float64, string) (ServerDTO, error)
	SetServerGPUBudgets(context.Context, auth.Token, string, SetGPUBudgetsRequest) ([]GPUBudgetDTO, error)
	SetServerHTTPSSwitchOverride(context.Context, auth.Token, string, string) (ServerDTO, error)
	SetServerNetbird(context.Context, auth.Token, string, bool, string, []string, bool, string, bool, bool) (ServerDTO, error)
	SetServiceAdminGroups(context.Context, auth.Token, string, []string) (ServiceDTO, error)
	SetUserLimits(context.Context, auth.Token, string, LimitConfigDTO) (UserLimitsDTO, error)
	SetUserPreference(context.Context, string, string, json.RawMessage) error
	SyncApplicationModels(context.Context, auth.Token, string) (SyncResultDTO, error)
	SyncApplicationModelsForApp(context.Context, routing.AIServer, routing.Application) (SyncResultDTO, error)
	SystemAdminModeRequirePassword(context.Context) bool
	SystemSettingsView(context.Context) SystemSettingsDTO
	TOTPMode(context.Context) string
	TestNetbird(context.Context, auth.Token, *NetbirdTestOverride) error
	TransferOwnership(context.Context, auth.Token, string, string) error
	TransferProject(context.Context, auth.Token, string, string) error
	UpdateApplication(context.Context, auth.Token, string, UpdateApplicationRequest) (ApplicationDTO, error)
	UpdateMapping(context.Context, auth.Token, string, UpdateMappingRequest) (ModelMappingDTO, error)
	UpdateModelGroup(context.Context, auth.Token, string, UpdateModelGroupRequest) (ModelGroupDTO, error)
	UpdateProject(context.Context, auth.Token, string, string, string) (ProjectDTO, error)
	UpdateResourceGroup(context.Context, auth.Token, string, UpdateResourceGroupRequest) (ResourceGroupDTO, error)
	UpdateServer(context.Context, auth.Token, string, UpdateServerRequest) (ServerDTO, error)
	UpdateService(context.Context, auth.Token, string, UpdateServiceRequest) (ServiceDTO, error)
	UpdateSystemSettings(context.Context, auth.Token, UpdateSystemSettingsRequest) (SystemSettingsDTO, error)
	UpdateToken(context.Context, auth.Token, string, UpdateTokenRequest) (TokenDTO, error)
	Usage(auth.Token, usage.Query) (usage.Page, error)
	UsageGroups(auth.Token, usage.Query, string) ([]UsageGroupDTO, error)
	UsageStats(auth.Token, usage.Query) (usage.Stats, error)
	UsageTimeSeries(auth.Token, usage.Query, int) (usage.TimeSeries, error)
	UserLimits(context.Context, string) (UserLimitsDTO, error)
	UserPreferences(context.Context, string) (map[string]json.RawMessage, error)
	UserTokens(context.Context, auth.Token, string) (TokenListResponse, error)
	VisibleUserIDs(context.Context, auth.Token) (map[string]bool, error)
	VisionProbeMode(context.Context) string
}

var _ API = (*Service)(nil)
