// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 OnPrem AI Gateway contributors

// Code generated by gowrap. DO NOT EDIT.
// template: ../tracing/templates/tracing-otelglobal.gowrap.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package portal

//go:generate gowrap gen -p op-ai-gateway/internal/portal -i API -t ../tracing/templates/tracing-otelglobal.gowrap.tmpl -o api_tracing_gen.go -v Prefix=portal.Service -v DecoratorName=APIWithTracing -l ""

import (
	"context"
	"encoding/json"
	"op-ai-gateway/internal/auth"
	"op-ai-gateway/internal/netbird"
	"op-ai-gateway/internal/routing"
	"op-ai-gateway/internal/usage"
	"time"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
)

// APIWithTracing instruments API with OpenTelemetry spans (one per
// ctx-carrying method) via the OTel global tracer. Non-ctx methods pass through
// untraced. It is generated same-package as the interface so it must NOT import
// internal/tracing (that package imports provider, which would form a cycle).
type APIWithTracing struct {
	API
}

// NewAPIWithTracing wraps base so every ctx-carrying call opens a span.
func NewAPIWithTracing(base API) API {
	return &APIWithTracing{API: base}
}

// _APIWithTracingTracer is resolved ONCE from the OTel global (installed by
// internal/tracing.Setup) and reused per call, avoiding the two process-global
// tracer-provider lookup mutexes otel.Tracer(name) takes on every wrapped call —
// keeping the disabled (default) path cheap. Set at package-init, never reassigned.
var _APIWithTracingTracer = otel.Tracer("op-ai-gateway")

func (_d *APIWithTracing) ActiveAgentPresenceTimeoutSeconds(ctx context.Context) (i1 int) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ActiveAgentPresenceTimeoutSeconds")
	defer span.End()
	return _d.API.ActiveAgentPresenceTimeoutSeconds(ctx)
}

func (_d *APIWithTracing) AddGroupMembers(ctx context.Context, t1 auth.Token, s1 string, sa1 []string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.AddGroupMembers")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AddGroupMembers(ctx, t1, s1, sa1)
}

func (_d *APIWithTracing) AddProjectGroups(ctx context.Context, t1 auth.Token, s1 string, sa1 []string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.AddProjectGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AddProjectGroups(ctx, t1, s1, sa1)
}

func (_d *APIWithTracing) AddProjectMembers(ctx context.Context, t1 auth.Token, s1 string, sa1 []string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.AddProjectMembers")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AddProjectMembers(ctx, t1, s1, sa1)
}

func (_d *APIWithTracing) AddServerToResourceGroup(ctx context.Context, t1 auth.Token, s1 string, s2 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.AddServerToResourceGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AddServerToResourceGroup(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) AddUserToAdminGroup(ctx context.Context, t1 auth.Token, s1 string, s2 string, s3 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.AddUserToAdminGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AddUserToAdminGroup(ctx, t1, s1, s2, s3)
}

func (_d *APIWithTracing) AdminOwnerCandidates(ctx context.Context, t1 auth.Token) (aa1 []AdminOwnerCandidateDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.AdminOwnerCandidates")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AdminOwnerCandidates(ctx, t1)
}

func (_d *APIWithTracing) AgentCertificate(ctx context.Context, s1 string) (a1 AgentCertificateDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.AgentCertificate")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AgentCertificate(ctx, s1)
}

func (_d *APIWithTracing) AgentProxyRoutes(ctx context.Context, s1 string) (a1 AgentProxyRoutesDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.AgentProxyRoutes")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AgentProxyRoutes(ctx, s1)
}

func (_d *APIWithTracing) AgentRuntimeConfig(ctx context.Context, s1 string) (a1 AgentRuntimeConfigDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.AgentRuntimeConfig")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AgentRuntimeConfig(ctx, s1)
}

func (_d *APIWithTracing) AgentTokenStatus(ctx context.Context, t1 auth.Token, s1 string) (a1 AgentTokenDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.AgentTokenStatus")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AgentTokenStatus(ctx, t1, s1)
}

func (_d *APIWithTracing) AllowedServerIDs(ctx context.Context, t1 auth.Token, sa1 []string) (m1 map[string]bool, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.AllowedServerIDs")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AllowedServerIDs(ctx, t1, sa1)
}

func (_d *APIWithTracing) AuthorizeBenchmarkScope(ctx context.Context, t1 auth.Token, s1 string, s2 string) (a1 routing.AIServer, ba1 []BenchmarkTargetView, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.AuthorizeBenchmarkScope")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AuthorizeBenchmarkScope(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) AuthorizeRunAsToken(ctx context.Context, t1 auth.Token, s1 string) (t2 auth.Token, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.AuthorizeRunAsToken")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AuthorizeRunAsToken(ctx, t1, s1)
}

func (_d *APIWithTracing) AuthorizeServerManage(ctx context.Context, t1 auth.Token, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.AuthorizeServerManage")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AuthorizeServerManage(ctx, t1, s1)
}

func (_d *APIWithTracing) CaptureDetail(t1 auth.Token, s1 string) (c1 CaptureDetail, err error) {
	return _d.API.CaptureDetail(t1, s1)
}

func (_d *APIWithTracing) CertEdgeRequireHTTPSChecked(ctx context.Context) (b1 bool) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CertEdgeRequireHTTPSChecked")
	defer span.End()
	return _d.API.CertEdgeRequireHTTPSChecked(ctx)
}

func (_d *APIWithTracing) CertMeshRequireTLSChecked(ctx context.Context) (b1 bool) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CertMeshRequireTLSChecked")
	defer span.End()
	return _d.API.CertMeshRequireTLSChecked(ctx)
}

func (_d *APIWithTracing) CertMeshTLSSeparateActive(ctx context.Context) (b1 bool, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CertMeshTLSSeparateActive")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CertMeshTLSSeparateActive(ctx)
}

func (_d *APIWithTracing) CertModuleChecked(ctx context.Context) (b1 bool) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CertModuleChecked")
	defer span.End()
	return _d.API.CertModuleChecked(ctx)
}

func (_d *APIWithTracing) CertificateCABundlePEM(ctx context.Context) (s1 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CertificateCABundlePEM")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CertificateCABundlePEM(ctx)
}

func (_d *APIWithTracing) CertificateCAView(ctx context.Context) (c2 CertificateCADTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CertificateCAView")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CertificateCAView(ctx)
}

func (_d *APIWithTracing) CertificatesView(ctx context.Context) (ca1 []CertificateDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CertificatesView")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CertificatesView(ctx)
}

func (_d *APIWithTracing) CheckpointAssistant(ctx context.Context, t1 auth.Token, s1 string, a1 AssistantTurn) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CheckpointAssistant")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CheckpointAssistant(ctx, t1, s1, a1)
}

func (_d *APIWithTracing) CommitAssistant(ctx context.Context, t1 auth.Token, s1 string, a1 AssistantTurn, s2 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CommitAssistant")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CommitAssistant(ctx, t1, s1, a1, s2)
}

func (_d *APIWithTracing) CreateApplication(ctx context.Context, t1 auth.Token, s1 string, c2 CreateApplicationRequest) (a1 ApplicationDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CreateApplication")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CreateApplication(ctx, t1, s1, c2)
}

func (_d *APIWithTracing) CreateChat(ctx context.Context, t1 auth.Token, c2 CreateChatRequest) (c3 ChatDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CreateChat")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CreateChat(ctx, t1, c2)
}

func (_d *APIWithTracing) CreateGatewaySetupKey(ctx context.Context, t1 auth.Token) (s1 string, s2 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CreateGatewaySetupKey")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CreateGatewaySetupKey(ctx, t1)
}

func (_d *APIWithTracing) CreateGroup(ctx context.Context, t1 auth.Token, c2 CreateGroupInput) (u1 UserGroupDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CreateGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CreateGroup(ctx, t1, c2)
}

func (_d *APIWithTracing) CreateMapping(ctx context.Context, t1 auth.Token, s1 string, c2 CreateMappingRequest) (m1 ModelMappingDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CreateMapping")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CreateMapping(ctx, t1, s1, c2)
}

func (_d *APIWithTracing) CreateModelGroup(ctx context.Context, t1 auth.Token, c2 CreateModelGroupRequest) (m1 ModelGroupDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CreateModelGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CreateModelGroup(ctx, t1, c2)
}

func (_d *APIWithTracing) CreateProject(ctx context.Context, t1 auth.Token, c2 CreateProjectInput) (p1 ProjectDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CreateProject")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CreateProject(ctx, t1, c2)
}

func (_d *APIWithTracing) CreateResourceGroup(ctx context.Context, t1 auth.Token, c2 CreateResourceGroupRequest) (r1 ResourceGroupDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CreateResourceGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CreateResourceGroup(ctx, t1, c2)
}

func (_d *APIWithTracing) CreateServer(ctx context.Context, t1 auth.Token, c2 CreateServerRequest) (s1 ServerDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CreateServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CreateServer(ctx, t1, c2)
}

func (_d *APIWithTracing) CreateService(ctx context.Context, t1 auth.Token, c2 CreateServiceRequest) (s1 ServiceDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CreateService")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CreateService(ctx, t1, c2)
}

func (_d *APIWithTracing) CreateServiceToken(ctx context.Context, t1 auth.Token, s1 string, c2 CreateServiceTokenRequest) (c3 CreateServiceTokenResponse, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CreateServiceToken")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CreateServiceToken(ctx, t1, s1, c2)
}

func (_d *APIWithTracing) CreateToken(ctx context.Context, t1 auth.Token, c2 CreateTokenRequest) (c3 CreateTokenResponse, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CreateToken")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CreateToken(ctx, t1, c2)
}

func (_d *APIWithTracing) CurrencyUsdPerEur(ctx context.Context) (f1 float64) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CurrencyUsdPerEur")
	defer span.End()
	return _d.API.CurrencyUsdPerEur(ctx)
}

func (_d *APIWithTracing) CurrentUser(ctx context.Context, t1 auth.Token) (c2 CurrentUser, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.CurrentUser")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.CurrentUser(ctx, t1)
}

func (_d *APIWithTracing) Dashboard(ctx context.Context, t1 auth.Token) (d1 DashboardResponse) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.Dashboard")
	defer span.End()
	return _d.API.Dashboard(ctx, t1)
}

func (_d *APIWithTracing) DeleteApplication(ctx context.Context, t1 auth.Token, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DeleteApplication")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DeleteApplication(ctx, t1, s1)
}

func (_d *APIWithTracing) DeleteCapture(t1 auth.Token, s1 string) (err error) {
	return _d.API.DeleteCapture(t1, s1)
}

func (_d *APIWithTracing) DeleteChat(ctx context.Context, t1 auth.Token, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DeleteChat")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DeleteChat(ctx, t1, s1)
}

func (_d *APIWithTracing) DeleteGroup(ctx context.Context, t1 auth.Token, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DeleteGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DeleteGroup(ctx, t1, s1)
}

func (_d *APIWithTracing) DeleteMapping(ctx context.Context, t1 auth.Token, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DeleteMapping")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DeleteMapping(ctx, t1, s1)
}

func (_d *APIWithTracing) DeleteModelGroup(ctx context.Context, t1 auth.Token, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DeleteModelGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DeleteModelGroup(ctx, t1, s1)
}

func (_d *APIWithTracing) DeleteProject(ctx context.Context, t1 auth.Token, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DeleteProject")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DeleteProject(ctx, t1, s1)
}

func (_d *APIWithTracing) DeleteResourceGroup(ctx context.Context, t1 auth.Token, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DeleteResourceGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DeleteResourceGroup(ctx, t1, s1)
}

func (_d *APIWithTracing) DeleteRuntimeSpec(ctx context.Context, t1 auth.Token, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DeleteRuntimeSpec")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DeleteRuntimeSpec(ctx, t1, s1)
}

func (_d *APIWithTracing) DeleteServer(ctx context.Context, t1 auth.Token, s1 string, b1 bool) (b2 bool, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DeleteServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DeleteServer(ctx, t1, s1, b1)
}

func (_d *APIWithTracing) DeleteService(ctx context.Context, t1 auth.Token, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DeleteService")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DeleteService(ctx, t1, s1)
}

func (_d *APIWithTracing) DeleteServiceToken(ctx context.Context, t1 auth.Token, s1 string, s2 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DeleteServiceToken")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DeleteServiceToken(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) DeleteToken(ctx context.Context, t1 auth.Token, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DeleteToken")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DeleteToken(ctx, t1, s1)
}

func (_d *APIWithTracing) DemoteManager(ctx context.Context, t1 auth.Token, s1 string, s2 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DemoteManager")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DemoteManager(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) DetachProjectToken(ctx context.Context, t1 auth.Token, s1 string, s2 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DetachProjectToken")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DetachProjectToken(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) DisplayNames(ctx context.Context, sa1 []string) (m1 map[string]string) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.DisplayNames")
	defer span.End()
	return _d.API.DisplayNames(ctx, sa1)
}

func (_d *APIWithTracing) EdgeCertificateBundlePEM(ctx context.Context) (s1 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.EdgeCertificateBundlePEM")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.EdgeCertificateBundlePEM(ctx)
}

func (_d *APIWithTracing) EdgeCertificateKeyPEM(ctx context.Context) (s1 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.EdgeCertificateKeyPEM")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.EdgeCertificateKeyPEM(ctx)
}

func (_d *APIWithTracing) EdgeCertificateView(ctx context.Context) (e1 EdgeCertificateDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.EdgeCertificateView")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.EdgeCertificateView(ctx)
}

func (_d *APIWithTracing) EdgeProxyConfig(ctx context.Context) (s1 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.EdgeProxyConfig")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.EdgeProxyConfig(ctx)
}

func (_d *APIWithTracing) EnrollGatewaySidecar(ctx context.Context, t1 auth.Token) (s1 string, s2 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.EnrollGatewaySidecar")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.EnrollGatewaySidecar(ctx, t1)
}

func (_d *APIWithTracing) ExternalThemeAsset(s1 string, s2 string) (s3 string, b1 bool) {
	return _d.API.ExternalThemeAsset(s1, s2)
}

func (_d *APIWithTracing) GatewayCARotationPendingServers(ctx context.Context) (ca1 []CertificateServerRefDTO) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.GatewayCARotationPendingServers")
	defer span.End()
	return _d.API.GatewayCARotationPendingServers(ctx)
}

func (_d *APIWithTracing) GatewayMeshCertificate(ctx context.Context) (g1 GatewayMeshCertificateMaterial, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.GatewayMeshCertificate")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.GatewayMeshCertificate(ctx)
}

func (_d *APIWithTracing) GenerateAgentToken(ctx context.Context, t1 auth.Token, s1 string) (g1 GenerateAgentTokenResponse, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.GenerateAgentToken")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.GenerateAgentToken(ctx, t1, s1)
}

func (_d *APIWithTracing) GetApplication(ctx context.Context, t1 auth.Token, s1 string) (a1 ApplicationDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.GetApplication")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.GetApplication(ctx, t1, s1)
}

func (_d *APIWithTracing) GetChat(ctx context.Context, t1 auth.Token, s1 string) (c2 ChatDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.GetChat")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.GetChat(ctx, t1, s1)
}

func (_d *APIWithTracing) GetCoResidency(ctx context.Context, t1 auth.Token, s1 string) (c2 CoResidencyDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.GetCoResidency")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.GetCoResidency(ctx, t1, s1)
}

func (_d *APIWithTracing) GetModelGroup(ctx context.Context, t1 auth.Token, s1 string) (m1 ModelGroupDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.GetModelGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.GetModelGroup(ctx, t1, s1)
}

func (_d *APIWithTracing) GetResourceGroup(ctx context.Context, t1 auth.Token, s1 string) (r1 ResourceGroupDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.GetResourceGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.GetResourceGroup(ctx, t1, s1)
}

func (_d *APIWithTracing) GetRuntimeSpec(ctx context.Context, t1 auth.Token, s1 string) (r1 RuntimeSpecDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.GetRuntimeSpec")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.GetRuntimeSpec(ctx, t1, s1)
}

func (_d *APIWithTracing) GetServer(ctx context.Context, t1 auth.Token, s1 string) (s2 ServerDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.GetServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.GetServer(ctx, t1, s1)
}

func (_d *APIWithTracing) GetServerGPUBudgets(ctx context.Context, t1 auth.Token, s1 string) (ga1 []GPUBudgetDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.GetServerGPUBudgets")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.GetServerGPUBudgets(ctx, t1, s1)
}

func (_d *APIWithTracing) GetService(ctx context.Context, t1 auth.Token, s1 string) (s2 ServiceDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.GetService")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.GetService(ctx, t1, s1)
}

func (_d *APIWithTracing) GroupMemberCandidates(ctx context.Context, t1 auth.Token, s1 string) (ua1 []UserRefDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.GroupMemberCandidates")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.GroupMemberCandidates(ctx, t1, s1)
}

func (_d *APIWithTracing) GroupMembers(ctx context.Context, t1 auth.Token, s1 string) (ua1 []UserGroupMemberDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.GroupMembers")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.GroupMembers(ctx, t1, s1)
}

func (_d *APIWithTracing) HTTPSSwitchUnreachableApps(ctx context.Context) (ha1 []HTTPSSwitchUnreachableDTO) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.HTTPSSwitchUnreachableApps")
	defer span.End()
	return _d.API.HTTPSSwitchUnreachableApps(ctx)
}

func (_d *APIWithTracing) HealthCheckIntervalSeconds(ctx context.Context) (i1 int) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.HealthCheckIntervalSeconds")
	defer span.End()
	return _d.API.HealthCheckIntervalSeconds(ctx)
}

func (_d *APIWithTracing) ListApplications(ctx context.Context, t1 auth.Token, s1 string) (a1 ApplicationListResponse, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ListApplications")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ListApplications(ctx, t1, s1)
}

func (_d *APIWithTracing) ListChats(ctx context.Context, t1 auth.Token) (ca1 []ChatSummaryDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ListChats")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ListChats(ctx, t1)
}

func (_d *APIWithTracing) ListGroups(ctx context.Context, t1 auth.Token) (g1 GroupLandscapeDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ListGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ListGroups(ctx, t1)
}

func (_d *APIWithTracing) ListInvitations(ctx context.Context, t1 auth.Token) (ia1 []InvitationDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ListInvitations")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ListInvitations(ctx, t1)
}

func (_d *APIWithTracing) ListMappings(ctx context.Context, t1 auth.Token, s1 string) (m1 MappingListResponse, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ListMappings")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ListMappings(ctx, t1, s1)
}

func (_d *APIWithTracing) ListModelGroups(ctx context.Context, t1 auth.Token) (m1 ModelGroupsResponse, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ListModelGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ListModelGroups(ctx, t1)
}

func (_d *APIWithTracing) ListProjects(ctx context.Context, t1 auth.Token) (pa1 []ProjectDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ListProjects")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ListProjects(ctx, t1)
}

func (_d *APIWithTracing) ListResourceGroups(ctx context.Context, t1 auth.Token) (ra1 []ResourceGroupDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ListResourceGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ListResourceGroups(ctx, t1)
}

func (_d *APIWithTracing) ListServers(ctx context.Context, t1 auth.Token) (s1 ServerListResponse, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ListServers")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ListServers(ctx, t1)
}

func (_d *APIWithTracing) ListServiceTokens(ctx context.Context, t1 auth.Token, s1 string) (sa1 []ServiceTokenDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ListServiceTokens")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ListServiceTokens(ctx, t1, s1)
}

func (_d *APIWithTracing) ListServices(ctx context.Context, t1 auth.Token) (sa1 []ServiceDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ListServices")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ListServices(ctx, t1)
}

func (_d *APIWithTracing) ListTokens(ctx context.Context, t1 auth.Token) (t2 TokenListResponse, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ListTokens")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ListTokens(ctx, t1)
}

func (_d *APIWithTracing) ManageModels(ctx context.Context, t1 auth.Token) (m1 ModelsResponse) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ManageModels")
	defer span.End()
	return _d.API.ManageModels(ctx, t1)
}

func (_d *APIWithTracing) ManageableUserIDs(ctx context.Context, t1 auth.Token) (m1 map[string]bool, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ManageableUserIDs")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ManageableUserIDs(ctx, t1)
}

func (_d *APIWithTracing) MappingBenchmarks(ctx context.Context, t1 auth.Token, s1 string, i1 int) (ba1 []BenchmarkRunDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.MappingBenchmarks")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.MappingBenchmarks(ctx, t1, s1, i1)
}

func (_d *APIWithTracing) MeshTLSPendingServers(ctx context.Context) (ca1 []CertificateServerRefDTO) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.MeshTLSPendingServers")
	defer span.End()
	return _d.API.MeshTLSPendingServers(ctx)
}

func (_d *APIWithTracing) ModelOfferingFor(ctx context.Context, t1 auth.Token, s1 string) (m1 ModelOffering) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ModelOfferingFor")
	defer span.End()
	return _d.API.ModelOfferingFor(ctx, t1, s1)
}

func (_d *APIWithTracing) ModelServers(ctx context.Context, t1 auth.Token, s1 string) (ma1 []ModelServerDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ModelServers")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ModelServers(ctx, t1, s1)
}

func (_d *APIWithTracing) Models(ctx context.Context, t1 auth.Token) (m1 ModelsResponse) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.Models")
	defer span.End()
	return _d.API.Models(ctx, t1)
}

func (_d *APIWithTracing) ModelsForFlavor(ctx context.Context, t1 auth.Token, s1 string) (sa1 []string) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ModelsForFlavor")
	defer span.End()
	return _d.API.ModelsForFlavor(ctx, t1, s1)
}

func (_d *APIWithTracing) MyProjects(ctx context.Context, t1 auth.Token) (pa1 []ProjectRefDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.MyProjects")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.MyProjects(ctx, t1)
}

func (_d *APIWithTracing) NetbirdAgentDownloadOnly(ctx context.Context) (b1 bool) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.NetbirdAgentDownloadOnly")
	defer span.End()
	return _d.API.NetbirdAgentDownloadOnly(ctx)
}

func (_d *APIWithTracing) NetbirdConfig(ctx context.Context) (n1 NetbirdConfig, b1 bool, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.NetbirdConfig")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.NetbirdConfig(ctx)
}

func (_d *APIWithTracing) NetbirdGatewayPeerID(ctx context.Context) (s1 string) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.NetbirdGatewayPeerID")
	defer span.End()
	return _d.API.NetbirdGatewayPeerID(ctx)
}

func (_d *APIWithTracing) NetbirdGroups(ctx context.Context) (ga1 []netbird.Group, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.NetbirdGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.NetbirdGroups(ctx)
}

func (_d *APIWithTracing) NetbirdKeyFileConfigured() (b1 bool) {
	return _d.API.NetbirdKeyFileConfigured()
}

func (_d *APIWithTracing) NetbirdModuleChecked(ctx context.Context) (b1 bool) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.NetbirdModuleChecked")
	defer span.End()
	return _d.API.NetbirdModuleChecked(ctx)
}

func (_d *APIWithTracing) NetbirdModuleEnabled(ctx context.Context) (b1 bool) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.NetbirdModuleEnabled")
	defer span.End()
	return _d.API.NetbirdModuleEnabled(ctx)
}

func (_d *APIWithTracing) NetbirdNetwork(ctx context.Context) (n1 NetbirdNetworkDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.NetbirdNetwork")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.NetbirdNetwork(ctx)
}

func (_d *APIWithTracing) NetbirdOnly(ctx context.Context) (b1 bool) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.NetbirdOnly")
	defer span.End()
	return _d.API.NetbirdOnly(ctx)
}

func (_d *APIWithTracing) NetbirdPeers(ctx context.Context) (pa1 []netbird.Peer, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.NetbirdPeers")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.NetbirdPeers(ctx)
}

func (_d *APIWithTracing) NetbirdPolicyContext(ctx context.Context) (n1 NetbirdPolicyContextDTO) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.NetbirdPolicyContext")
	defer span.End()
	return _d.API.NetbirdPolicyContext(ctx)
}

func (_d *APIWithTracing) NetbirdTokenStatus(ctx context.Context) (n1 NetbirdTokenStatusDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.NetbirdTokenStatus")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.NetbirdTokenStatus(ctx)
}

func (_d *APIWithTracing) PrepareChatRun(ctx context.Context, t1 auth.Token, s1 string, p1 PrepareRunRequest) (ca1 []ChatAPIMessage, c2 ChatRunSettings, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.PrepareChatRun")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.PrepareChatRun(ctx, t1, s1, p1)
}

func (_d *APIWithTracing) ProbeEdgeTLS(ctx context.Context) (e1 EdgeProbeDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ProbeEdgeTLS")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ProbeEdgeTLS(ctx)
}

func (_d *APIWithTracing) ProjectCandidates(ctx context.Context, t1 auth.Token, s1 string) (ua1 []UserRefDTO, ga1 []GroupRefDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ProjectCandidates")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ProjectCandidates(ctx, t1, s1)
}

func (_d *APIWithTracing) ProjectMembersView(ctx context.Context, t1 auth.Token, s1 string) (p1 ProjectMembersDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ProjectMembersView")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ProjectMembersView(ctx, t1, s1)
}

func (_d *APIWithTracing) ProjectTokens(ctx context.Context, t1 auth.Token, s1 string) (p1 ProjectTokensView, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ProjectTokens")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ProjectTokens(ctx, t1, s1)
}

func (_d *APIWithTracing) PromoteManager(ctx context.Context, t1 auth.Token, s1 string, s2 string, b1 bool, b2 bool, b3 bool, b4 bool, b5 bool) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.PromoteManager")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.PromoteManager(ctx, t1, s1, s2, b1, b2, b3, b4, b5)
}

func (_d *APIWithTracing) PublicCertificateBundlePEM(ctx context.Context, s1 string) (s2 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.PublicCertificateBundlePEM")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.PublicCertificateBundlePEM(ctx, s1)
}

func (_d *APIWithTracing) PublicCertificateKeyPEM(ctx context.Context, s1 string) (s2 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.PublicCertificateKeyPEM")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.PublicCertificateKeyPEM(ctx, s1)
}

func (_d *APIWithTracing) PublicLanguage(ctx context.Context) (s1 string) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.PublicLanguage")
	defer span.End()
	return _d.API.PublicLanguage(ctx)
}

func (_d *APIWithTracing) PublicTheme(ctx context.Context) (s1 string) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.PublicTheme")
	defer span.End()
	return _d.API.PublicTheme(ctx)
}

func (_d *APIWithTracing) PublicThemeView(ctx context.Context) (t1 ThemePublicView) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.PublicThemeView")
	defer span.End()
	return _d.API.PublicThemeView(ctx)
}

func (_d *APIWithTracing) PutRuntimeSpec(ctx context.Context, t1 auth.Token, s1 string, p1 PutRuntimeSpecRequest) (r1 RuntimeSpecDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.PutRuntimeSpec")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.PutRuntimeSpec(ctx, t1, s1, p1)
}

func (_d *APIWithTracing) ReassignGroupsOwnedBy(ctx context.Context, t1 auth.Token, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ReassignGroupsOwnedBy")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ReassignGroupsOwnedBy(ctx, t1, s1)
}

func (_d *APIWithTracing) ReconcileCertificates(ctx context.Context) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ReconcileCertificates")
	defer span.End()
	_d.API.ReconcileCertificates(ctx)
	return
}

func (_d *APIWithTracing) ReconcileGatewayPeer(ctx context.Context) (s1 string, b1 bool, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ReconcileGatewayPeer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ReconcileGatewayPeer(ctx)
}

func (_d *APIWithTracing) RegenerateNetbirdKey(ctx context.Context, t1 auth.Token, s1 string) (s2 string, s3 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.RegenerateNetbirdKey")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.RegenerateNetbirdKey(ctx, t1, s1)
}

func (_d *APIWithTracing) ReissueAllCertificates(ctx context.Context, t1 auth.Token) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ReissueAllCertificates")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ReissueAllCertificates(ctx, t1)
}

func (_d *APIWithTracing) ReissueEdgeCertificate(ctx context.Context, t1 auth.Token) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ReissueEdgeCertificate")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ReissueEdgeCertificate(ctx, t1)
}

func (_d *APIWithTracing) RemoveGroupMember(ctx context.Context, t1 auth.Token, s1 string, s2 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.RemoveGroupMember")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.RemoveGroupMember(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) RemoveProjectGroup(ctx context.Context, t1 auth.Token, s1 string, s2 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.RemoveProjectGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.RemoveProjectGroup(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) RemoveProjectMember(ctx context.Context, t1 auth.Token, s1 string, s2 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.RemoveProjectMember")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.RemoveProjectMember(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) RemoveServerFromResourceGroup(ctx context.Context, t1 auth.Token, s1 string, s2 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.RemoveServerFromResourceGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.RemoveServerFromResourceGroup(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) RenameGroup(ctx context.Context, t1 auth.Token, s1 string, s2 string) (u1 UserGroupDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.RenameGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.RenameGroup(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) RenewCertificateNow(ctx context.Context, t1 auth.Token, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.RenewCertificateNow")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.RenewCertificateNow(ctx, t1, s1)
}

func (_d *APIWithTracing) ResolveGatewayPeerDNS(ctx context.Context) (s1 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ResolveGatewayPeerDNS")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ResolveGatewayPeerDNS(ctx)
}

func (_d *APIWithTracing) ResolveGatewayPeerIP(ctx context.Context) (s1 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ResolveGatewayPeerIP")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ResolveGatewayPeerIP(ctx)
}

func (_d *APIWithTracing) ResolveInviteAdminGroup(ctx context.Context, t1 auth.Token, s1 string) (s2 string, s3 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ResolveInviteAdminGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ResolveInviteAdminGroup(ctx, t1, s1)
}

func (_d *APIWithTracing) ResourceGroupAdminGroupCandidates(ctx context.Context, t1 auth.Token) (aa1 []AdminGroupCandidateDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ResourceGroupAdminGroupCandidates")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ResourceGroupAdminGroupCandidates(ctx, t1)
}

func (_d *APIWithTracing) ResourceGroupProvisionCandidates(ctx context.Context, t1 auth.Token, s1 string) (r1 ResourceGroupProvisionCandidatesDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ResourceGroupProvisionCandidates")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ResourceGroupProvisionCandidates(ctx, t1, s1)
}

func (_d *APIWithTracing) ResourceGroupProvisionsView(ctx context.Context, t1 auth.Token, s1 string) (ra1 []ResourceGroupProvisionDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ResourceGroupProvisionsView")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ResourceGroupProvisionsView(ctx, t1, s1)
}

func (_d *APIWithTracing) ResourceGroupServerCandidates(ctx context.Context, t1 auth.Token, s1 string) (ra1 []ResourceGroupServerRefDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ResourceGroupServerCandidates")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ResourceGroupServerCandidates(ctx, t1, s1)
}

func (_d *APIWithTracing) RespondInvitation(ctx context.Context, t1 auth.Token, s1 string, b1 bool) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.RespondInvitation")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.RespondInvitation(ctx, t1, s1, b1)
}

func (_d *APIWithTracing) RevokeAgentToken(ctx context.Context, t1 auth.Token, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.RevokeAgentToken")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.RevokeAgentToken(ctx, t1, s1)
}

func (_d *APIWithTracing) RotateCertificateCA(ctx context.Context, t1 auth.Token) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.RotateCertificateCA")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.RotateCertificateCA(ctx, t1)
}

func (_d *APIWithTracing) RotateNetbirdToken(ctx context.Context, t1 auth.Token) (r1 RotateNetbirdTokenResult, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.RotateNetbirdToken")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.RotateNetbirdToken(ctx, t1)
}

func (_d *APIWithTracing) RotateServiceToken(ctx context.Context, t1 auth.Token, s1 string, s2 string) (c2 CreateServiceTokenResponse, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.RotateServiceToken")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.RotateServiceToken(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) RotateToken(ctx context.Context, t1 auth.Token, s1 string) (c2 CreateTokenResponse, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.RotateToken")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.RotateToken(ctx, t1, s1)
}

func (_d *APIWithTracing) RuntimeWarnings(ctx context.Context, t1 auth.Token, s1 string) (sa1 []string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.RuntimeWarnings")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.RuntimeWarnings(ctx, t1, s1)
}

func (_d *APIWithTracing) SMTPRuntimeConfig(ctx context.Context) (s1 SMTPRuntimeConfig, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SMTPRuntimeConfig")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SMTPRuntimeConfig(ctx)
}

func (_d *APIWithTracing) SaveChat(ctx context.Context, t1 auth.Token, s1 string, u1 UpdateChatRequest) (c2 ChatDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SaveChat")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SaveChat(ctx, t1, s1, u1)
}

func (_d *APIWithTracing) ServerAdminGroupCandidates(ctx context.Context, t1 auth.Token) (aa1 []AdminGroupCandidateDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ServerAdminGroupCandidates")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ServerAdminGroupCandidates(ctx, t1)
}

func (_d *APIWithTracing) ServerAvailability(ctx context.Context, t1 auth.Token, s1 string, d1 time.Duration) (sa1 []routing.ServerAvailabilitySample, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ServerAvailability")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ServerAvailability(ctx, t1, s1, d1)
}

func (_d *APIWithTracing) ServerHardware(ctx context.Context, t1 auth.Token, s1 string) (s2 routing.ServerHardware, b1 bool, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ServerHardware")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ServerHardware(ctx, t1, s1)
}

func (_d *APIWithTracing) ServerModels(ctx context.Context, t1 auth.Token, s1 string) (sa1 []ServerModelDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ServerModels")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ServerModels(ctx, t1, s1)
}

func (_d *APIWithTracing) ServerOwnerResourceGroups(ctx context.Context, t1 auth.Token, s1 string) (sa1 []ServerResourceGroupDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ServerOwnerResourceGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ServerOwnerResourceGroups(ctx, t1, s1)
}

func (_d *APIWithTracing) ServerPerfHistory(ctx context.Context, t1 auth.Token, s1 string, d1 time.Duration) (ta1 []routing.TelemetrySample, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ServerPerfHistory")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ServerPerfHistory(ctx, t1, s1, d1)
}

func (_d *APIWithTracing) ServerRuntimeReportView(ctx context.Context, t1 auth.Token, s1 string) (s2 ServerRuntimeReportViewDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ServerRuntimeReportView")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ServerRuntimeReportView(ctx, t1, s1)
}

func (_d *APIWithTracing) ServiceAdminGroupCandidates(ctx context.Context, t1 auth.Token) (aa1 []AdminGroupCandidateDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.ServiceAdminGroupCandidates")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ServiceAdminGroupCandidates(ctx, t1)
}

func (_d *APIWithTracing) SetBenchmarkRuntimeSpecAdminState(ctx context.Context, s1 string, s2 string, s3 string) (r1 RuntimeSpecDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetBenchmarkRuntimeSpecAdminState")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetBenchmarkRuntimeSpecAdminState(ctx, s1, s2, s3)
}

func (_d *APIWithTracing) SetCaptureSecret(t1 auth.Token, s1 string, b1 bool) (err error) {
	return _d.API.SetCaptureSecret(t1, s1, b1)
}

func (_d *APIWithTracing) SetCoResidency(ctx context.Context, t1 auth.Token, s1 string, s2 SetCoResidencyRequest) (c2 CoResidencyDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetCoResidency")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetCoResidency(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) SetManagerPermissions(ctx context.Context, t1 auth.Token, s1 string, s2 string, b1 bool, b2 bool, b3 bool, b4 bool, b5 bool) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetManagerPermissions")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetManagerPermissions(ctx, t1, s1, s2, b1, b2, b3, b4, b5)
}

func (_d *APIWithTracing) SetModelVisibility(ctx context.Context, t1 auth.Token, s1 string, s2 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetModelVisibility")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetModelVisibility(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) SetNetbirdNetwork(ctx context.Context, t1 auth.Token, n1 NetbirdNetworkDTO) (n2 NetbirdNetworkDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetNetbirdNetwork")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetNetbirdNetwork(ctx, t1, n1)
}

func (_d *APIWithTracing) SetResourceGroupAdminGroups(ctx context.Context, t1 auth.Token, s1 string, sa1 []string) (r1 ResourceGroupDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetResourceGroupAdminGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetResourceGroupAdminGroups(ctx, t1, s1, sa1)
}

func (_d *APIWithTracing) SetResourceGroupProvisions(ctx context.Context, t1 auth.Token, s1 string, ra1 []routing.ResourceGroupProvision) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetResourceGroupProvisions")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetResourceGroupProvisions(ctx, t1, s1, ra1)
}

func (_d *APIWithTracing) SetResourceGroupServers(ctx context.Context, t1 auth.Token, s1 string, sa1 []string) (r1 ResourceGroupDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetResourceGroupServers")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetResourceGroupServers(ctx, t1, s1, sa1)
}

func (_d *APIWithTracing) SetServerAdminGroups(ctx context.Context, t1 auth.Token, s1 string, sa1 []string) (s2 ServerDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetServerAdminGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetServerAdminGroups(ctx, t1, s1, sa1)
}

func (_d *APIWithTracing) SetServerCertificateOverride(ctx context.Context, t1 auth.Token, s1 string, s2 string) (s3 ServerDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetServerCertificateOverride")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetServerCertificateOverride(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) SetServerEnergyConfig(ctx context.Context, t1 auth.Token, s1 string, f1 float64, f2 float64, f3 float64, f4 float64, s2 string) (s3 ServerDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetServerEnergyConfig")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetServerEnergyConfig(ctx, t1, s1, f1, f2, f3, f4, s2)
}

func (_d *APIWithTracing) SetServerGPUBudgets(ctx context.Context, t1 auth.Token, s1 string, s2 SetGPUBudgetsRequest) (ga1 []GPUBudgetDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetServerGPUBudgets")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetServerGPUBudgets(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) SetServerHTTPSSwitchOverride(ctx context.Context, t1 auth.Token, s1 string, s2 string) (s3 ServerDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetServerHTTPSSwitchOverride")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetServerHTTPSSwitchOverride(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) SetServerNetbird(ctx context.Context, t1 auth.Token, s1 string, b1 bool, s2 string, sa1 []string, b2 bool, s3 string, b3 bool, b4 bool) (s4 ServerDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetServerNetbird")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetServerNetbird(ctx, t1, s1, b1, s2, sa1, b2, s3, b3, b4)
}

func (_d *APIWithTracing) SetServiceAdminGroups(ctx context.Context, t1 auth.Token, s1 string, sa1 []string) (s2 ServiceDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetServiceAdminGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetServiceAdminGroups(ctx, t1, s1, sa1)
}

func (_d *APIWithTracing) SetUserLimits(ctx context.Context, t1 auth.Token, s1 string, l1 LimitConfigDTO) (u1 UserLimitsDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetUserLimits")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetUserLimits(ctx, t1, s1, l1)
}

func (_d *APIWithTracing) SetUserPreference(ctx context.Context, s1 string, s2 string, r1 json.RawMessage) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SetUserPreference")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetUserPreference(ctx, s1, s2, r1)
}

func (_d *APIWithTracing) SyncApplicationModels(ctx context.Context, t1 auth.Token, s1 string) (s2 SyncResultDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SyncApplicationModels")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SyncApplicationModels(ctx, t1, s1)
}

func (_d *APIWithTracing) SyncApplicationModelsForApp(ctx context.Context, a1 routing.AIServer, a2 routing.Application) (s1 SyncResultDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SyncApplicationModelsForApp")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SyncApplicationModelsForApp(ctx, a1, a2)
}

func (_d *APIWithTracing) SystemAdminModeRequirePassword(ctx context.Context) (b1 bool) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SystemAdminModeRequirePassword")
	defer span.End()
	return _d.API.SystemAdminModeRequirePassword(ctx)
}

func (_d *APIWithTracing) SystemSettingsView(ctx context.Context) (s1 SystemSettingsDTO) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.SystemSettingsView")
	defer span.End()
	return _d.API.SystemSettingsView(ctx)
}

func (_d *APIWithTracing) TOTPMode(ctx context.Context) (s1 string) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.TOTPMode")
	defer span.End()
	return _d.API.TOTPMode(ctx)
}

func (_d *APIWithTracing) TestNetbird(ctx context.Context, t1 auth.Token, np1 *NetbirdTestOverride) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.TestNetbird")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.TestNetbird(ctx, t1, np1)
}

func (_d *APIWithTracing) TransferOwnership(ctx context.Context, t1 auth.Token, s1 string, s2 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.TransferOwnership")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.TransferOwnership(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) TransferProject(ctx context.Context, t1 auth.Token, s1 string, s2 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.TransferProject")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.TransferProject(ctx, t1, s1, s2)
}

func (_d *APIWithTracing) UpdateApplication(ctx context.Context, t1 auth.Token, s1 string, u1 UpdateApplicationRequest) (a1 ApplicationDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.UpdateApplication")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UpdateApplication(ctx, t1, s1, u1)
}

func (_d *APIWithTracing) UpdateMapping(ctx context.Context, t1 auth.Token, s1 string, u1 UpdateMappingRequest) (m1 ModelMappingDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.UpdateMapping")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UpdateMapping(ctx, t1, s1, u1)
}

func (_d *APIWithTracing) UpdateModelGroup(ctx context.Context, t1 auth.Token, s1 string, u1 UpdateModelGroupRequest) (m1 ModelGroupDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.UpdateModelGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UpdateModelGroup(ctx, t1, s1, u1)
}

func (_d *APIWithTracing) UpdateProject(ctx context.Context, t1 auth.Token, s1 string, s2 string, s3 string) (p1 ProjectDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.UpdateProject")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UpdateProject(ctx, t1, s1, s2, s3)
}

func (_d *APIWithTracing) UpdateResourceGroup(ctx context.Context, t1 auth.Token, s1 string, u1 UpdateResourceGroupRequest) (r1 ResourceGroupDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.UpdateResourceGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UpdateResourceGroup(ctx, t1, s1, u1)
}

func (_d *APIWithTracing) UpdateServer(ctx context.Context, t1 auth.Token, s1 string, u1 UpdateServerRequest) (s2 ServerDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.UpdateServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UpdateServer(ctx, t1, s1, u1)
}

func (_d *APIWithTracing) UpdateService(ctx context.Context, t1 auth.Token, s1 string, u1 UpdateServiceRequest) (s2 ServiceDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.UpdateService")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UpdateService(ctx, t1, s1, u1)
}

func (_d *APIWithTracing) UpdateSystemSettings(ctx context.Context, t1 auth.Token, u1 UpdateSystemSettingsRequest) (s1 SystemSettingsDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.UpdateSystemSettings")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UpdateSystemSettings(ctx, t1, u1)
}

func (_d *APIWithTracing) UpdateToken(ctx context.Context, t1 auth.Token, s1 string, u1 UpdateTokenRequest) (t2 TokenDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.UpdateToken")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UpdateToken(ctx, t1, s1, u1)
}

func (_d *APIWithTracing) Usage(t1 auth.Token, q1 usage.Query) (p1 usage.Page, err error) {
	return _d.API.Usage(t1, q1)
}

func (_d *APIWithTracing) UsageGroups(t1 auth.Token, q1 usage.Query, s1 string) (ua1 []UsageGroupDTO, err error) {
	return _d.API.UsageGroups(t1, q1, s1)
}

func (_d *APIWithTracing) UsageStats(t1 auth.Token, q1 usage.Query) (s1 usage.Stats, err error) {
	return _d.API.UsageStats(t1, q1)
}

func (_d *APIWithTracing) UsageTimeSeries(t1 auth.Token, q1 usage.Query, i1 int) (t2 usage.TimeSeries, err error) {
	return _d.API.UsageTimeSeries(t1, q1, i1)
}

func (_d *APIWithTracing) UserLimits(ctx context.Context, s1 string) (u1 UserLimitsDTO, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.UserLimits")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UserLimits(ctx, s1)
}

func (_d *APIWithTracing) UserPreferences(ctx context.Context, s1 string) (m1 map[string]json.RawMessage, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.UserPreferences")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UserPreferences(ctx, s1)
}

func (_d *APIWithTracing) UserTokens(ctx context.Context, t1 auth.Token, s1 string) (t2 TokenListResponse, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.UserTokens")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UserTokens(ctx, t1, s1)
}

func (_d *APIWithTracing) VisibleUserIDs(ctx context.Context, t1 auth.Token) (m1 map[string]bool, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.VisibleUserIDs")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.VisibleUserIDs(ctx, t1)
}

func (_d *APIWithTracing) VisionProbeMode(ctx context.Context) (s1 string) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "portal.Service.VisionProbeMode")
	defer span.End()
	return _d.API.VisionProbeMode(ctx)
}
