// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 OnPrem AI Gateway contributors

// Code generated by interfacer; DO NOT EDIT

package account

import (
	"context"
	"op-ai-gateway/internal/store"
)

// API is an interface generated for "op-ai-gateway/internal/account.Service".
type API interface {
	AuthenticatePassword(context.Context, string, string) (store.User, error)
	ChangePassword(context.Context, string, string, string) error
	ConfirmTOTP(context.Context, string, string) (store.User, error)
	DisableTOTP(context.Context, string, string) error
	EnterSystemAdminMode(context.Context, string, string, bool) error
	ExitSystemAdminMode(context.Context, string) error
	InviteUser(context.Context, InviteInput, bool) (store.User, string, error)
	IssueSession(context.Context, store.User) (string, error)
	ListUsers(context.Context) ([]store.User, error)
	Login(context.Context, string, string) (store.User, string, error)
	Logout(context.Context, string) error
	ReissueInvite(context.Context, string) (store.User, string, error)
	ResetTOTP(context.Context, string) error
	ResolveSession(context.Context, string) (store.User, error)
	ResolveSessionDetail(context.Context, string) (store.User, store.Session, error)
	SetPassword(context.Context, string, string) (store.User, string, error)
	SetPendingTOTP(context.Context, string) (string, string, error)
	UpdateOwnProfile(context.Context, string, UserUpdate) (store.User, error)
	UpdateUser(context.Context, string, UserUpdate, bool) (store.User, error)
	UserByID(context.Context, string) (store.User, error)
	VerifyTOTP(store.User, string) bool
}

var _ API = (*Service)(nil)
