// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 OnPrem AI Gateway contributors

// Code generated by gowrap. DO NOT EDIT.
// template: ../tracing/templates/tracing-otelglobal.gowrap.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package account

//go:generate gowrap gen -p op-ai-gateway/internal/account -i API -t ../tracing/templates/tracing-otelglobal.gowrap.tmpl -o api_tracing_gen.go -v Prefix=account.Service -v DecoratorName=APIWithTracing -l ""

import (
	"context"
	"op-ai-gateway/internal/store"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
)

// APIWithTracing instruments API with OpenTelemetry spans (one per
// ctx-carrying method) via the OTel global tracer. Non-ctx methods pass through
// untraced. It is generated same-package as the interface so it must NOT import
// internal/tracing (that package imports provider, which would form a cycle).
type APIWithTracing struct {
	API
}

// NewAPIWithTracing wraps base so every ctx-carrying call opens a span.
func NewAPIWithTracing(base API) API {
	return &APIWithTracing{API: base}
}

// _APIWithTracingTracer is resolved ONCE from the OTel global (installed by
// internal/tracing.Setup) and reused per call, avoiding the two process-global
// tracer-provider lookup mutexes otel.Tracer(name) takes on every wrapped call —
// keeping the disabled (default) path cheap. Set at package-init, never reassigned.
var _APIWithTracingTracer = otel.Tracer("op-ai-gateway")

func (_d *APIWithTracing) AuthenticatePassword(ctx context.Context, s1 string, s2 string) (u1 store.User, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.AuthenticatePassword")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.AuthenticatePassword(ctx, s1, s2)
}

func (_d *APIWithTracing) ChangePassword(ctx context.Context, s1 string, s2 string, s3 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.ChangePassword")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ChangePassword(ctx, s1, s2, s3)
}

func (_d *APIWithTracing) ConfirmTOTP(ctx context.Context, s1 string, s2 string) (u1 store.User, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.ConfirmTOTP")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ConfirmTOTP(ctx, s1, s2)
}

func (_d *APIWithTracing) DisableTOTP(ctx context.Context, s1 string, s2 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.DisableTOTP")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.DisableTOTP(ctx, s1, s2)
}

func (_d *APIWithTracing) EnterSystemAdminMode(ctx context.Context, s1 string, s2 string, b1 bool) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.EnterSystemAdminMode")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.EnterSystemAdminMode(ctx, s1, s2, b1)
}

func (_d *APIWithTracing) ExitSystemAdminMode(ctx context.Context, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.ExitSystemAdminMode")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ExitSystemAdminMode(ctx, s1)
}

func (_d *APIWithTracing) InviteUser(ctx context.Context, i1 InviteInput, b1 bool) (u1 store.User, s1 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.InviteUser")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.InviteUser(ctx, i1, b1)
}

func (_d *APIWithTracing) IssueSession(ctx context.Context, u1 store.User) (s1 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.IssueSession")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.IssueSession(ctx, u1)
}

func (_d *APIWithTracing) ListUsers(ctx context.Context) (ua1 []store.User, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.ListUsers")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ListUsers(ctx)
}

func (_d *APIWithTracing) Login(ctx context.Context, s1 string, s2 string) (u1 store.User, s3 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.Login")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.Login(ctx, s1, s2)
}

func (_d *APIWithTracing) Logout(ctx context.Context, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.Logout")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.Logout(ctx, s1)
}

func (_d *APIWithTracing) ReissueInvite(ctx context.Context, s1 string) (u1 store.User, s2 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.ReissueInvite")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ReissueInvite(ctx, s1)
}

func (_d *APIWithTracing) ResetTOTP(ctx context.Context, s1 string) (err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.ResetTOTP")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ResetTOTP(ctx, s1)
}

func (_d *APIWithTracing) ResolveSession(ctx context.Context, s1 string) (u1 store.User, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.ResolveSession")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ResolveSession(ctx, s1)
}

func (_d *APIWithTracing) ResolveSessionDetail(ctx context.Context, s1 string) (u1 store.User, s2 store.Session, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.ResolveSessionDetail")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.ResolveSessionDetail(ctx, s1)
}

func (_d *APIWithTracing) SetPassword(ctx context.Context, s1 string, s2 string) (u1 store.User, s3 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.SetPassword")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetPassword(ctx, s1, s2)
}

func (_d *APIWithTracing) SetPendingTOTP(ctx context.Context, s1 string) (s2 string, s3 string, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.SetPendingTOTP")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.SetPendingTOTP(ctx, s1)
}

func (_d *APIWithTracing) UpdateOwnProfile(ctx context.Context, s1 string, u1 UserUpdate) (u2 store.User, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.UpdateOwnProfile")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UpdateOwnProfile(ctx, s1, u1)
}

func (_d *APIWithTracing) UpdateUser(ctx context.Context, s1 string, u1 UserUpdate, b1 bool) (u2 store.User, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.UpdateUser")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UpdateUser(ctx, s1, u1, b1)
}

func (_d *APIWithTracing) UserByID(ctx context.Context, s1 string) (u1 store.User, err error) {
	ctx, span := _APIWithTracingTracer.Start(ctx, "account.Service.UserByID")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.API.UserByID(ctx, s1)
}

func (_d *APIWithTracing) VerifyTOTP(u1 store.User, s1 string) (b1 bool) {
	return _d.API.VerifyTOTP(u1, s1)
}
