// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 OnPrem AI Gateway contributors

package gateway

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"net/http"
	"op-ai-gateway/internal/apierror"
	"op-ai-gateway/internal/auth"
	"op-ai-gateway/internal/inference"
	"op-ai-gateway/internal/provider"
	"op-ai-gateway/internal/routing"
	"sync/atomic"
	"time"
)

// errCodeStreamIdleTimeout and errCodeClientDisconnected are the two synthetic
// (never-hits-a-provider) terminal error codes a streamSession can classify a
// stream into, shared by recordUsage's errorCode column and each flavor's
// terminal-frame switch. They are distinct from any completionErrorCode value.
const (
	errCodeStreamIdleTimeout  = "provider.stream_idle_timeout"
	errCodeClientDisconnected = "provider.client_disconnected"
)

// streamSession holds the SSE lifecycle scaffold shared by completeStream,
// completeStreamResponses, and completeStreamAnthropic: resolve + active
// registration, response headers, the idle watchdog, the write-deadline-armed
// capture-teeing emit, terminal-status classification, and the recordUsage
// epilogue. Each of those functions keeps ONLY its own protocol frame shaping
// (chat.completion.chunk vs the Responses event sequence vs Anthropic's
// message_start/content_block_*/message_delta/message_stop events) and drives
// the shared machinery through this type's methods.
//
// A streamSession is used from a single goroutine (the request handler plus
// the synchronous provider-stream callback it drives) and is not safe for
// concurrent use from multiple goroutines.
type streamSession struct {
	s     *Server
	w     http.ResponseWriter
	r     *http.Request
	token auth.Token
	req   inference.Request // the original, client-facing request (echoed in frames)
	raw   []byte
	id    string
	start time.Time

	capturing bool
	target    routing.Target
	streamer  provider.StreamingClient
	flusher   http.Flusher

	providerReq inference.Request // req with target.ProviderModel applied, for the upstream call
	ctx         context.Context
	cancel      context.CancelFunc
	rc          *http.ResponseController
	idle        time.Duration
	watchdog    *time.Timer
	idledOut    atomic.Bool

	respBuf     bytes.Buffer
	capBytes    int
	captureSink *provider.CaptureSink
}

// beginStream resolves the routing target, verifies the provider supports
// streaming and that w can flush, registers the request as Active, writes the
// SSE response headers, and arms the idle watchdog. On any failure along the
// way it writes the appropriate response itself, records usage, and returns
// (nil, false) — the caller must return immediately without further action.
//
// fallback is the ONE per-protocol hook in this otherwise-identical preamble:
// when w can't flush, begin falls back to the buffered s.complete path, and
// fallback renders that flavor's non-streaming success body. id must be
// generated by the caller (nextRequestID(), called exactly once per request)
// so a fallback closure built before begin runs can embed it in the body it
// renders.
func (s *Server) beginStream(w http.ResponseWriter, r *http.Request, token auth.Token, req inference.Request, raw []byte, id string, fallback func(provider.Response) any) (*streamSession, bool) {
	start := time.Now()
	capturing := s.capturingEnabled(token)
	target, err := s.Resolver.Resolve(r.Context(), token, req)
	if err != nil {
		// pre-stream failure: the client has no stream yet, so return a normal JSON error
		slog.Warn("inference stream resolve failed", "path", r.URL.Path, "api_flavor", req.APIFlavor, "model", req.Model, "code", completionErrorCode(err), "status", completionHTTPStatus(err), "err", err)
		body := writeCompletionErrorCaptured(w, err)
		s.recordUsage(start, token, req, routing.Target{}, provider.Response{}, completionErrorCode(err), "error", usageMeta{ReqPath: r.URL.Path, HTTPStatus: completionHTTPStatus(err), ContentType: "application/json"}, id, buildCaptureInput(capturing, token.UserID, token.Secret, r, raw, w.Header(), body, completionHTTPStatus(err), req.APIFlavor))
		return nil, false
	}
	streamer, ok := s.Provider.(provider.StreamingClient)
	if !ok {
		body := writeJSONCaptured(w, http.StatusBadGateway, apierror.Response("provider.unavailable", "streaming not supported", ""))
		s.recordUsage(start, token, req, target, provider.Response{}, "provider.unavailable", "error", usageMeta{ReqPath: r.URL.Path, HTTPStatus: http.StatusBadGateway, ContentType: "application/json"}, id, buildCaptureInput(capturing, token.UserID, token.Secret, r, raw, w.Header(), body, http.StatusBadGateway, req.APIFlavor))
		return nil, false
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// Defensive: no flushing available — fall back to a buffered completion.
		// Registration happens inside complete (Stream:false), so this path is
		// tracked exactly once and never double-registered.
		s.complete(w, r, token, req, raw, fallback)
		return nil, false
	}

	// Register ONLY on the real streaming path (after the flusher check). The early
	// resolve-error and no-streamer branches above return before this and are
	// intentionally not tracked as active (they still record to the completed list).
	s.Active.Add(ActiveRequest{ID: id, UserID: token.UserID, TokenID: token.ID, TokenName: token.Name, ServiceID: token.ServiceID, ServiceName: token.ServiceName, ServerName: s.serverName(target.ServerID), ServerID: target.ServerID, Model: req.Model, APIFlavor: req.APIFlavor, ReqPath: r.URL.Path, ProviderPath: upstreamPath(target, req.APIFlavor), ProviderModel: effectiveProviderModel(target, req.Model), SessionID: req.ClientSessionID, SessionSource: req.SessionSource, AgentID: req.AgentID, Stream: true, StartedAt: start})

	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	w.WriteHeader(http.StatusOK)

	providerReq := req
	if target.ProviderModel != "" {
		providerReq.Model = target.ProviderModel
	}

	idle := s.streamIdleTimeout // 0 = disabled (unbounded; only client disconnect ends the stream)
	ctx, cancel := context.WithCancel(r.Context())
	ss := &streamSession{
		s: s, w: w, r: r, token: token, req: req, raw: raw, id: id, start: start,
		capturing: capturing, target: target, streamer: streamer, flusher: flusher,
		providerReq: providerReq, ctx: ctx, cancel: cancel, rc: http.NewResponseController(w),
		idle: idle, capBytes: s.captureMaxBytes,
	}
	if idle > 0 {
		ss.watchdog = time.AfterFunc(idle, func() { ss.idledOut.Store(true); cancel() })
	}
	// When capturing on the translate path, thread a capture sink so the provider
	// records the translated upstream request + raw upstream response.
	if capturing {
		ss.captureSink = provider.NewCaptureSink(s.captureMaxBytes)
		ss.ctx = provider.WithCaptureSink(ss.ctx, ss.captureSink)
	}
	// Attach the resolved application's per-app upstream credential (fail-open).
	ss.ctx = s.upstreamAuthCtx(ss.ctx, target)
	return ss, true
}

// close releases the session's resources: it stops the idle watchdog, cancels
// the stream context, and removes the request from the Active list — in that
// order, mirroring the LIFO order of the equivalent defers this scaffold used
// to declare inline. The caller must `defer ss.close()` immediately after a
// successful beginStream.
func (ss *streamSession) close() {
	if ss.watchdog != nil {
		ss.watchdog.Stop()
	}
	ss.cancel()
	ss.s.Active.Remove(ss.id)
}

// emit is the single client-SSE write path: it re-arms the write deadline to a
// fresh idle window, writes frame verbatim, flushes, and — when capturing —
// tees the identical bytes into respBuf, bounded by capBytes (~1 MB even with
// the idle watchdog disabled; buildCaptureEnvelope then flags truncated and
// clips to the cap). armWrite -> write -> flush order is unchanged, and the tee
// append happens only after a successful write so the write deadline and frame
// ordering are untouched. respBuf is written only from this provider-stream
// goroutine (serial emit) so no mutex is needed.
func (ss *streamSession) emit(frame string) error {
	if ss.idle > 0 {
		_ = ss.rc.SetWriteDeadline(time.Now().Add(ss.idle))
	}
	if _, err := fmt.Fprint(ss.w, frame); err != nil {
		return err
	}
	ss.flusher.Flush()
	if ss.capturing && ss.respBuf.Len() <= ss.capBytes {
		ss.respBuf.WriteString(frame)
	}
	return nil
}

// stream drives the provider's CompleteStream with handler, resetting the idle
// watchdog on every event exactly like each flavor's inline callback used to
// (StreamEventError is unused: providers report failures via CompleteStream's
// return value, not events).
func (ss *streamSession) stream(handler func(inference.StreamEvent) error) error {
	return ss.streamer.CompleteStream(ss.ctx, ss.target, ss.providerReq, func(ev inference.StreamEvent) error {
		if ss.watchdog != nil {
			ss.watchdog.Reset(ss.idle)
		}
		return handler(ev)
	})
}

// terminalStatus classifies how the stream ended from the CompleteStream
// return value and the idle-watchdog/request-context state armed by
// beginStream, and returns the (status, errorCode) recordUsage expects along
// with clientGone (the disconnect race guard some flavors also need for their
// own post-switch decisions, e.g. completeStream's trailing [DONE]).
//
// clientGone is computed unconditionally, exactly once, up front — matching the
// original scaffold's single `clientGone := r.Context().Err() != nil &&
// !idledOut.Load()` — so it reflects the true disconnect state regardless of
// which case below fires; !idledOut guards the rare both-fired race (watchdog
// cancel racing a real client disconnect) so an idle timeout is never
// mislabeled as client-gone.
//
// It also logs the outcome — identical across all three translate flavors for
// the idle/disconnect/error cases; the success case is logged by the caller,
// which alone knows the flavor-specific usage/tool-call tallies to log.
func (ss *streamSession) terminalStatus(streamErr error) (status, errorCode string, clientGone bool) {
	clientGone = ss.r.Context().Err() != nil && !ss.idledOut.Load()
	switch {
	case streamErr == nil:
		return "success", "", clientGone
	case ss.idledOut.Load():
		slog.Error("inference stream idle timeout", "path", ss.r.URL.Path, "api_flavor", ss.req.APIFlavor, "model", ss.req.Model, "server", ss.s.serverName(ss.target.ServerID), "idle", ss.idle.String())
		return "error", errCodeStreamIdleTimeout, clientGone
	case clientGone:
		// Client disconnected — the socket is gone, so write no frame.
		slog.Debug("inference stream client disconnected", "path", ss.r.URL.Path, "api_flavor", ss.req.APIFlavor, "model", ss.req.Model, "server", ss.s.serverName(ss.target.ServerID))
		return "error", errCodeClientDisconnected, clientGone
	default:
		errorCode = completionErrorCode(streamErr)
		slog.Error("inference stream failed", "path", ss.r.URL.Path, "api_flavor", ss.req.APIFlavor, "model", ss.req.Model, "server", ss.s.serverName(ss.target.ServerID), "code", errorCode, "err", streamErr)
		return "error", errorCode, clientGone
	}
}

// finish runs the recordUsage/capture epilogue common to all three flavors: the
// SSE response headers (200, text/event-stream) were already written before
// streaming began, regardless of any mid-stream error, so both are always
// reported as such here.
func (ss *streamSession) finish(usage inference.Usage, status, errorCode string) {
	streamCI := buildCaptureInput(ss.capturing, ss.token.UserID, ss.token.Secret, ss.r, ss.raw, ss.w.Header(), ss.respBuf.Bytes(), http.StatusOK, ss.req.APIFlavor)
	attachTranslatedCapture(streamCI, ss.captureSink)
	ss.s.recordUsage(ss.start, ss.token, ss.req, ss.target, provider.Response{Usage: usage}, errorCode, status, usageMeta{ReqPath: ss.r.URL.Path, HTTPStatus: http.StatusOK, ContentType: "text/event-stream"}, ss.id, streamCI)
}
