// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 OnPrem AI Gateway contributors

// Code generated by gowrap. DO NOT EDIT.
// template: templates/tracing.gowrap.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package tracing

//go:generate gowrap gen -p op-ai-gateway/internal/routing -i Store -t templates/tracing.gowrap.tmpl -o routingstore_gen.go -v Prefix=routing.Store -v DecoratorName=RoutingStoreWithTracing -l ""

import (
	"context"
	_sourceRouting "op-ai-gateway/internal/routing"
	"time"

	"go.opentelemetry.io/otel/codes"
)

// RoutingStoreWithTracing instruments _sourceRouting.Store with OpenTelemetry spans
// (one per ctx-carrying method). Non-ctx methods pass through untraced.
type RoutingStoreWithTracing struct {
	_sourceRouting.Store
}

// NewRoutingStoreWithTracing wraps base so every ctx-carrying call opens a span.
func NewRoutingStoreWithTracing(base _sourceRouting.Store) _sourceRouting.Store {
	return &RoutingStoreWithTracing{Store: base}
}

func (_d *RoutingStoreWithTracing) AIServerByID(ctx context.Context, id string) (a1 _sourceRouting.AIServer, err error) {
	ctx, span := Start(ctx, "routing.Store.AIServerByID")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.AIServerByID(ctx, id)
}

func (_d *RoutingStoreWithTracing) AIServers(ctx context.Context) (aa1 []_sourceRouting.AIServer, err error) {
	ctx, span := Start(ctx, "routing.Store.AIServers")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.AIServers(ctx)
}

func (_d *RoutingStoreWithTracing) ActiveMappingsForModel(ctx context.Context, gatewayModel string, apiFlavor string) (ma1 []_sourceRouting.MappingCandidate, err error) {
	ctx, span := Start(ctx, "routing.Store.ActiveMappingsForModel")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ActiveMappingsForModel(ctx, gatewayModel, apiFlavor)
}

func (_d *RoutingStoreWithTracing) Affinity(ctx context.Context, key _sourceRouting.AffinityKey) (r1 _sourceRouting.RouteAffinity, b1 bool, err error) {
	ctx, span := Start(ctx, "routing.Store.Affinity")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.Affinity(ctx, key)
}

func (_d *RoutingStoreWithTracing) AgentTokenByServer(ctx context.Context, serverID string) (a1 _sourceRouting.AgentToken, b1 bool, err error) {
	ctx, span := Start(ctx, "routing.Store.AgentTokenByServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.AgentTokenByServer(ctx, serverID)
}

func (_d *RoutingStoreWithTracing) ApplicationByID(ctx context.Context, id string) (a1 _sourceRouting.Application, err error) {
	ctx, span := Start(ctx, "routing.Store.ApplicationByID")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ApplicationByID(ctx, id)
}

func (_d *RoutingStoreWithTracing) ApplicationsByServer(ctx context.Context, serverID string) (aa1 []_sourceRouting.Application, err error) {
	ctx, span := Start(ctx, "routing.Store.ApplicationsByServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ApplicationsByServer(ctx, serverID)
}

func (_d *RoutingStoreWithTracing) BenchmarkRunsByMapping(ctx context.Context, mappingID string, limit int) (ba1 []_sourceRouting.BenchmarkRun, err error) {
	ctx, span := Start(ctx, "routing.Store.BenchmarkRunsByMapping")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.BenchmarkRunsByMapping(ctx, mappingID, limit)
}

func (_d *RoutingStoreWithTracing) CertificateByDomain(ctx context.Context, domain string) (c2 _sourceRouting.Certificate, err error) {
	ctx, span := Start(ctx, "routing.Store.CertificateByDomain")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.CertificateByDomain(ctx, domain)
}

func (_d *RoutingStoreWithTracing) CertificateByServer(ctx context.Context, serverID string) (c2 _sourceRouting.Certificate, err error) {
	ctx, span := Start(ctx, "routing.Store.CertificateByServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.CertificateByServer(ctx, serverID)
}

func (_d *RoutingStoreWithTracing) Certificates(ctx context.Context) (ca1 []_sourceRouting.Certificate, err error) {
	ctx, span := Start(ctx, "routing.Store.Certificates")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.Certificates(ctx)
}

func (_d *RoutingStoreWithTracing) CoResidencyRulesByApplication(ctx context.Context, appID string) (ca1 []_sourceRouting.CoResidencyRule, err error) {
	ctx, span := Start(ctx, "routing.Store.CoResidencyRulesByApplication")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.CoResidencyRulesByApplication(ctx, appID)
}

func (_d *RoutingStoreWithTracing) CreateAIServer(ctx context.Context, host _sourceRouting.AIServer) (err error) {
	ctx, span := Start(ctx, "routing.Store.CreateAIServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.CreateAIServer(ctx, host)
}

func (_d *RoutingStoreWithTracing) CreateApplication(ctx context.Context, app _sourceRouting.Application) (err error) {
	ctx, span := Start(ctx, "routing.Store.CreateApplication")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.CreateApplication(ctx, app)
}

func (_d *RoutingStoreWithTracing) CreateMapping(ctx context.Context, mapping _sourceRouting.ModelMapping) (err error) {
	ctx, span := Start(ctx, "routing.Store.CreateMapping")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.CreateMapping(ctx, mapping)
}

func (_d *RoutingStoreWithTracing) CreateModelGroup(ctx context.Context, group _sourceRouting.ModelGroup) (err error) {
	ctx, span := Start(ctx, "routing.Store.CreateModelGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.CreateModelGroup(ctx, group)
}

func (_d *RoutingStoreWithTracing) CreateResourceGroup(ctx context.Context, rg _sourceRouting.ResourceGroup) (err error) {
	ctx, span := Start(ctx, "routing.Store.CreateResourceGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.CreateResourceGroup(ctx, rg)
}

func (_d *RoutingStoreWithTracing) CreateService(ctx context.Context, svc _sourceRouting.Service) (err error) {
	ctx, span := Start(ctx, "routing.Store.CreateService")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.CreateService(ctx, svc)
}

func (_d *RoutingStoreWithTracing) DeleteAIServer(ctx context.Context, id string) (err error) {
	ctx, span := Start(ctx, "routing.Store.DeleteAIServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.DeleteAIServer(ctx, id)
}

func (_d *RoutingStoreWithTracing) DeleteAffinity(ctx context.Context, key _sourceRouting.AffinityKey) (err error) {
	ctx, span := Start(ctx, "routing.Store.DeleteAffinity")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.DeleteAffinity(ctx, key)
}

func (_d *RoutingStoreWithTracing) DeleteAgentTokenByServer(ctx context.Context, serverID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.DeleteAgentTokenByServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.DeleteAgentTokenByServer(ctx, serverID)
}

func (_d *RoutingStoreWithTracing) DeleteApplication(ctx context.Context, id string) (err error) {
	ctx, span := Start(ctx, "routing.Store.DeleteApplication")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.DeleteApplication(ctx, id)
}

func (_d *RoutingStoreWithTracing) DeleteCertificate(ctx context.Context, domain string) (err error) {
	ctx, span := Start(ctx, "routing.Store.DeleteCertificate")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.DeleteCertificate(ctx, domain)
}

func (_d *RoutingStoreWithTracing) DeleteMapping(ctx context.Context, id string) (err error) {
	ctx, span := Start(ctx, "routing.Store.DeleteMapping")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.DeleteMapping(ctx, id)
}

func (_d *RoutingStoreWithTracing) DeleteModelGroup(ctx context.Context, id string) (err error) {
	ctx, span := Start(ctx, "routing.Store.DeleteModelGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.DeleteModelGroup(ctx, id)
}

func (_d *RoutingStoreWithTracing) DeletePrincipalLimits(ctx context.Context, principalType string, principalID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.DeletePrincipalLimits")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.DeletePrincipalLimits(ctx, principalType, principalID)
}

func (_d *RoutingStoreWithTracing) DeleteResourceGroup(ctx context.Context, id string) (err error) {
	ctx, span := Start(ctx, "routing.Store.DeleteResourceGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.DeleteResourceGroup(ctx, id)
}

func (_d *RoutingStoreWithTracing) DeleteRuntimeSpec(ctx context.Context, id string) (err error) {
	ctx, span := Start(ctx, "routing.Store.DeleteRuntimeSpec")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.DeleteRuntimeSpec(ctx, id)
}

func (_d *RoutingStoreWithTracing) DeleteService(ctx context.Context, id string) (err error) {
	ctx, span := Start(ctx, "routing.Store.DeleteService")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.DeleteService(ctx, id)
}

func (_d *RoutingStoreWithTracing) GroupMembersByGroup(ctx context.Context, groupID string) (ga1 []_sourceRouting.GroupMember, err error) {
	ctx, span := Start(ctx, "routing.Store.GroupMembersByGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.GroupMembersByGroup(ctx, groupID)
}

func (_d *RoutingStoreWithTracing) InsertBenchmarkRun(ctx context.Context, run _sourceRouting.BenchmarkRun) (err error) {
	ctx, span := Start(ctx, "routing.Store.InsertBenchmarkRun")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.InsertBenchmarkRun(ctx, run)
}

func (_d *RoutingStoreWithTracing) InsertServerAvailabilitySample(ctx context.Context, sample _sourceRouting.ServerAvailabilitySample) (err error) {
	ctx, span := Start(ctx, "routing.Store.InsertServerAvailabilitySample")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.InsertServerAvailabilitySample(ctx, sample)
}

func (_d *RoutingStoreWithTracing) InsertTelemetrySample(ctx context.Context, sample _sourceRouting.TelemetrySample) (err error) {
	ctx, span := Start(ctx, "routing.Store.InsertTelemetrySample")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.InsertTelemetrySample(ctx, sample)
}

func (_d *RoutingStoreWithTracing) LookupAgentToken(ctx context.Context, secretHash string) (serverID string, ok bool, err error) {
	ctx, span := Start(ctx, "routing.Store.LookupAgentToken")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.LookupAgentToken(ctx, secretHash)
}

func (_d *RoutingStoreWithTracing) MappingByID(ctx context.Context, id string) (m1 _sourceRouting.ModelMapping, err error) {
	ctx, span := Start(ctx, "routing.Store.MappingByID")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.MappingByID(ctx, id)
}

func (_d *RoutingStoreWithTracing) MappingsByApplication(ctx context.Context, applicationID string) (ma1 []_sourceRouting.ModelMapping, err error) {
	ctx, span := Start(ctx, "routing.Store.MappingsByApplication")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.MappingsByApplication(ctx, applicationID)
}

func (_d *RoutingStoreWithTracing) MappingsByServer(ctx context.Context, serverID string) (ma1 []_sourceRouting.ModelMapping, err error) {
	ctx, span := Start(ctx, "routing.Store.MappingsByServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.MappingsByServer(ctx, serverID)
}

func (_d *RoutingStoreWithTracing) ModelGroupByID(ctx context.Context, id string) (m1 _sourceRouting.ModelGroup, err error) {
	ctx, span := Start(ctx, "routing.Store.ModelGroupByID")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ModelGroupByID(ctx, id)
}

func (_d *RoutingStoreWithTracing) ModelGroups(ctx context.Context) (ma1 []_sourceRouting.ModelGroup, err error) {
	ctx, span := Start(ctx, "routing.Store.ModelGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ModelGroups(ctx)
}

func (_d *RoutingStoreWithTracing) ModelSettingByName(ctx context.Context, name string) (m1 _sourceRouting.ModelSetting, b1 bool, err error) {
	ctx, span := Start(ctx, "routing.Store.ModelSettingByName")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ModelSettingByName(ctx, name)
}

func (_d *RoutingStoreWithTracing) ModelSettings(ctx context.Context) (ma1 []_sourceRouting.ModelSetting, err error) {
	ctx, span := Start(ctx, "routing.Store.ModelSettings")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ModelSettings(ctx)
}

func (_d *RoutingStoreWithTracing) PrincipalLimits(ctx context.Context, principalType string, principalID string) (l1 _sourceRouting.LimitConfig, b1 bool, err error) {
	ctx, span := Start(ctx, "routing.Store.PrincipalLimits")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.PrincipalLimits(ctx, principalType, principalID)
}

func (_d *RoutingStoreWithTracing) ProvisionedResourceGroupIDs(ctx context.Context) (m1 map[string]bool, err error) {
	ctx, span := Start(ctx, "routing.Store.ProvisionedResourceGroupIDs")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ProvisionedResourceGroupIDs(ctx)
}

func (_d *RoutingStoreWithTracing) PruneBenchmarkRuns(ctx context.Context, before time.Time) (err error) {
	ctx, span := Start(ctx, "routing.Store.PruneBenchmarkRuns")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.PruneBenchmarkRuns(ctx, before)
}

func (_d *RoutingStoreWithTracing) PruneServerAvailabilitySamples(ctx context.Context, before time.Time) (err error) {
	ctx, span := Start(ctx, "routing.Store.PruneServerAvailabilitySamples")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.PruneServerAvailabilitySamples(ctx, before)
}

func (_d *RoutingStoreWithTracing) PruneTelemetrySamples(ctx context.Context, before time.Time) (err error) {
	ctx, span := Start(ctx, "routing.Store.PruneTelemetrySamples")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.PruneTelemetrySamples(ctx, before)
}

func (_d *RoutingStoreWithTracing) RemoveResourceGroupAdminGroup(ctx context.Context, rgID string, groupID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.RemoveResourceGroupAdminGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.RemoveResourceGroupAdminGroup(ctx, rgID, groupID)
}

func (_d *RoutingStoreWithTracing) RemoveResourceGroupProvision(ctx context.Context, rgID string, kind string, targetID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.RemoveResourceGroupProvision")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.RemoveResourceGroupProvision(ctx, rgID, kind, targetID)
}

func (_d *RoutingStoreWithTracing) RemoveResourceGroupServer(ctx context.Context, rgID string, serverID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.RemoveResourceGroupServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.RemoveResourceGroupServer(ctx, rgID, serverID)
}

func (_d *RoutingStoreWithTracing) RemoveServerAdminGroup(ctx context.Context, serverID string, groupID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.RemoveServerAdminGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.RemoveServerAdminGroup(ctx, serverID, groupID)
}

func (_d *RoutingStoreWithTracing) RemoveServiceAdminGroup(ctx context.Context, serviceID string, groupID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.RemoveServiceAdminGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.RemoveServiceAdminGroup(ctx, serviceID, groupID)
}

func (_d *RoutingStoreWithTracing) ResourceGroupAdminGroups(ctx context.Context, rgID string) (sa1 []string, err error) {
	ctx, span := Start(ctx, "routing.Store.ResourceGroupAdminGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ResourceGroupAdminGroups(ctx, rgID)
}

func (_d *RoutingStoreWithTracing) ResourceGroupByID(ctx context.Context, id string) (r1 _sourceRouting.ResourceGroup, err error) {
	ctx, span := Start(ctx, "routing.Store.ResourceGroupByID")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ResourceGroupByID(ctx, id)
}

func (_d *RoutingStoreWithTracing) ResourceGroupIDsByProvisionTargets(ctx context.Context, kind string, targetIDs []string) (sa1 []string, err error) {
	ctx, span := Start(ctx, "routing.Store.ResourceGroupIDsByProvisionTargets")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ResourceGroupIDsByProvisionTargets(ctx, kind, targetIDs)
}

func (_d *RoutingStoreWithTracing) ResourceGroupProvisions(ctx context.Context, rgID string) (ra1 []_sourceRouting.ResourceGroupProvision, err error) {
	ctx, span := Start(ctx, "routing.Store.ResourceGroupProvisions")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ResourceGroupProvisions(ctx, rgID)
}

func (_d *RoutingStoreWithTracing) ResourceGroupServers(ctx context.Context, rgID string) (sa1 []string, err error) {
	ctx, span := Start(ctx, "routing.Store.ResourceGroupServers")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ResourceGroupServers(ctx, rgID)
}

func (_d *RoutingStoreWithTracing) ResourceGroups(ctx context.Context) (ra1 []_sourceRouting.ResourceGroup, err error) {
	ctx, span := Start(ctx, "routing.Store.ResourceGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ResourceGroups(ctx)
}

func (_d *RoutingStoreWithTracing) ResourceGroupsByAdminGroups(ctx context.Context, groupIDs []string) (ra1 []_sourceRouting.ResourceGroup, err error) {
	ctx, span := Start(ctx, "routing.Store.ResourceGroupsByAdminGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ResourceGroupsByAdminGroups(ctx, groupIDs)
}

func (_d *RoutingStoreWithTracing) ResourceGroupsByServer(ctx context.Context, serverID string) (ra1 []_sourceRouting.ResourceGroup, err error) {
	ctx, span := Start(ctx, "routing.Store.ResourceGroupsByServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ResourceGroupsByServer(ctx, serverID)
}

func (_d *RoutingStoreWithTracing) RuntimeSpecByMapping(ctx context.Context, mappingID string) (r1 _sourceRouting.RuntimeSpec, b1 bool, err error) {
	ctx, span := Start(ctx, "routing.Store.RuntimeSpecByMapping")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.RuntimeSpecByMapping(ctx, mappingID)
}

func (_d *RoutingStoreWithTracing) RuntimeSpecGPUs(ctx context.Context, specID string) (ra1 []_sourceRouting.RuntimeSpecGPU, err error) {
	ctx, span := Start(ctx, "routing.Store.RuntimeSpecGPUs")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.RuntimeSpecGPUs(ctx, specID)
}

func (_d *RoutingStoreWithTracing) RuntimeSpecsByApplication(ctx context.Context, appID string) (ra1 []_sourceRouting.RuntimeSpec, err error) {
	ctx, span := Start(ctx, "routing.Store.RuntimeSpecsByApplication")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.RuntimeSpecsByApplication(ctx, appID)
}

func (_d *RoutingStoreWithTracing) ServerAdminGroups(ctx context.Context, serverID string) (sa1 []string, err error) {
	ctx, span := Start(ctx, "routing.Store.ServerAdminGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ServerAdminGroups(ctx, serverID)
}

func (_d *RoutingStoreWithTracing) ServerAvailabilitySamples(ctx context.Context, serverID string, from time.Time, to time.Time, limit int) (sa1 []_sourceRouting.ServerAvailabilitySample, err error) {
	ctx, span := Start(ctx, "routing.Store.ServerAvailabilitySamples")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ServerAvailabilitySamples(ctx, serverID, from, to, limit)
}

func (_d *RoutingStoreWithTracing) ServerGPUBudgets(ctx context.Context, serverID string) (sa1 []_sourceRouting.ServerGPUBudget, err error) {
	ctx, span := Start(ctx, "routing.Store.ServerGPUBudgets")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ServerGPUBudgets(ctx, serverID)
}

func (_d *RoutingStoreWithTracing) ServerHardwareByServer(ctx context.Context, serverID string) (s1 _sourceRouting.ServerHardware, b1 bool, err error) {
	ctx, span := Start(ctx, "routing.Store.ServerHardwareByServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ServerHardwareByServer(ctx, serverID)
}

func (_d *RoutingStoreWithTracing) ServerOwners(ctx context.Context, serverID string) (sa1 []string, err error) {
	ctx, span := Start(ctx, "routing.Store.ServerOwners")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ServerOwners(ctx, serverID)
}

func (_d *RoutingStoreWithTracing) ServersByAdminGroups(ctx context.Context, groupIDs []string) (aa1 []_sourceRouting.AIServer, err error) {
	ctx, span := Start(ctx, "routing.Store.ServersByAdminGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ServersByAdminGroups(ctx, groupIDs)
}

func (_d *RoutingStoreWithTracing) ServersByOwner(ctx context.Context, userID string) (aa1 []_sourceRouting.AIServer, err error) {
	ctx, span := Start(ctx, "routing.Store.ServersByOwner")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ServersByOwner(ctx, userID)
}

func (_d *RoutingStoreWithTracing) ServiceAdminGroups(ctx context.Context, serviceID string) (sa1 []string, err error) {
	ctx, span := Start(ctx, "routing.Store.ServiceAdminGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ServiceAdminGroups(ctx, serviceID)
}

func (_d *RoutingStoreWithTracing) ServiceAllowedModels(ctx context.Context, serviceID string) (sa1 []string, err error) {
	ctx, span := Start(ctx, "routing.Store.ServiceAllowedModels")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ServiceAllowedModels(ctx, serviceID)
}

func (_d *RoutingStoreWithTracing) ServiceByID(ctx context.Context, id string) (s1 _sourceRouting.Service, err error) {
	ctx, span := Start(ctx, "routing.Store.ServiceByID")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ServiceByID(ctx, id)
}

func (_d *RoutingStoreWithTracing) ServiceDelegates(ctx context.Context, serviceID string) (sa1 []_sourceRouting.ServiceDelegate, err error) {
	ctx, span := Start(ctx, "routing.Store.ServiceDelegates")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ServiceDelegates(ctx, serviceID)
}

func (_d *RoutingStoreWithTracing) Services(ctx context.Context) (sa1 []_sourceRouting.Service, err error) {
	ctx, span := Start(ctx, "routing.Store.Services")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.Services(ctx)
}

func (_d *RoutingStoreWithTracing) ServicesByAdminGroups(ctx context.Context, groupIDs []string) (sa1 []_sourceRouting.Service, err error) {
	ctx, span := Start(ctx, "routing.Store.ServicesByAdminGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ServicesByAdminGroups(ctx, groupIDs)
}

func (_d *RoutingStoreWithTracing) ServicesByDelegate(ctx context.Context, userID string) (sa1 []_sourceRouting.Service, err error) {
	ctx, span := Start(ctx, "routing.Store.ServicesByDelegate")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.ServicesByDelegate(ctx, userID)
}

func (_d *RoutingStoreWithTracing) SetCoResidencyRules(ctx context.Context, appID string, rules []_sourceRouting.CoResidencyRule) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetCoResidencyRules")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetCoResidencyRules(ctx, appID, rules)
}

func (_d *RoutingStoreWithTracing) SetGroupMembers(ctx context.Context, groupID string, members []_sourceRouting.GroupMember) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetGroupMembers")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetGroupMembers(ctx, groupID, members)
}

func (_d *RoutingStoreWithTracing) SetPrincipalLimits(ctx context.Context, principalType string, principalID string, cfg _sourceRouting.LimitConfig) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetPrincipalLimits")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetPrincipalLimits(ctx, principalType, principalID, cfg)
}

func (_d *RoutingStoreWithTracing) SetResourceGroupAdminGroup(ctx context.Context, rgID string, groupID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetResourceGroupAdminGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetResourceGroupAdminGroup(ctx, rgID, groupID)
}

func (_d *RoutingStoreWithTracing) SetResourceGroupProvision(ctx context.Context, rgID string, kind string, targetID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetResourceGroupProvision")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetResourceGroupProvision(ctx, rgID, kind, targetID)
}

func (_d *RoutingStoreWithTracing) SetResourceGroupProvisions(ctx context.Context, rgID string, provisions []_sourceRouting.ResourceGroupProvision) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetResourceGroupProvisions")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetResourceGroupProvisions(ctx, rgID, provisions)
}

func (_d *RoutingStoreWithTracing) SetResourceGroupServer(ctx context.Context, rgID string, serverID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetResourceGroupServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetResourceGroupServer(ctx, rgID, serverID)
}

func (_d *RoutingStoreWithTracing) SetRuntimeSpecGPUs(ctx context.Context, specID string, gpus []_sourceRouting.RuntimeSpecGPU) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetRuntimeSpecGPUs")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetRuntimeSpecGPUs(ctx, specID, gpus)
}

func (_d *RoutingStoreWithTracing) SetServerAdminGroup(ctx context.Context, serverID string, groupID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetServerAdminGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetServerAdminGroup(ctx, serverID, groupID)
}

func (_d *RoutingStoreWithTracing) SetServerGPUBudgets(ctx context.Context, serverID string, budgets []_sourceRouting.ServerGPUBudget) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetServerGPUBudgets")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetServerGPUBudgets(ctx, serverID, budgets)
}

func (_d *RoutingStoreWithTracing) SetServerHealth(ctx context.Context, serverID string, health string) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetServerHealth")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetServerHealth(ctx, serverID, health)
}

func (_d *RoutingStoreWithTracing) SetServerOwners(ctx context.Context, serverID string, userIDs []string) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetServerOwners")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetServerOwners(ctx, serverID, userIDs)
}

func (_d *RoutingStoreWithTracing) SetServiceAdminGroup(ctx context.Context, serviceID string, groupID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetServiceAdminGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetServiceAdminGroup(ctx, serviceID, groupID)
}

func (_d *RoutingStoreWithTracing) SetServiceAllowedModels(ctx context.Context, serviceID string, models []string) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetServiceAllowedModels")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetServiceAllowedModels(ctx, serviceID, models)
}

func (_d *RoutingStoreWithTracing) SetServiceDelegates(ctx context.Context, serviceID string, delegates []_sourceRouting.ServiceDelegate) (err error) {
	ctx, span := Start(ctx, "routing.Store.SetServiceDelegates")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.SetServiceDelegates(ctx, serviceID, delegates)
}

func (_d *RoutingStoreWithTracing) TelemetryByServer(ctx context.Context, serverID string) (s1 _sourceRouting.ServerTelemetry, b1 bool, err error) {
	ctx, span := Start(ctx, "routing.Store.TelemetryByServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.TelemetryByServer(ctx, serverID)
}

func (_d *RoutingStoreWithTracing) TelemetrySamples(ctx context.Context, serverID string, from time.Time, to time.Time, limit int) (ta1 []_sourceRouting.TelemetrySample, err error) {
	ctx, span := Start(ctx, "routing.Store.TelemetrySamples")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.TelemetrySamples(ctx, serverID, from, to, limit)
}

func (_d *RoutingStoreWithTracing) UpdateAIServer(ctx context.Context, host _sourceRouting.AIServer) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateAIServer")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateAIServer(ctx, host)
}

func (_d *RoutingStoreWithTracing) UpdateApplication(ctx context.Context, app _sourceRouting.Application) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateApplication")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateApplication(ctx, app)
}

func (_d *RoutingStoreWithTracing) UpdateMapping(ctx context.Context, mapping _sourceRouting.ModelMapping) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateMapping")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateMapping(ctx, mapping)
}

func (_d *RoutingStoreWithTracing) UpdateMappingBenchmarkMetrics(ctx context.Context, id string, genTPS float64, promptTPS float64, loadMS int, at time.Time) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateMappingBenchmarkMetrics")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateMappingBenchmarkMetrics(ctx, id, genTPS, promptTPS, loadMS, at)
}

func (_d *RoutingStoreWithTracing) UpdateMappingCapacityMetrics(ctx context.Context, id string, maxConcurrency int, recommendedConcurrency int, genTPSAtCapacity float64, at time.Time) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateMappingCapacityMetrics")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateMappingCapacityMetrics(ctx, id, maxConcurrency, recommendedConcurrency, genTPSAtCapacity, at)
}

func (_d *RoutingStoreWithTracing) UpdateMappingContextProbe(ctx context.Context, id string, contextSize int, at time.Time) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateMappingContextProbe")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateMappingContextProbe(ctx, id, contextSize, at)
}

func (_d *RoutingStoreWithTracing) UpdateMappingEnergyEWMA(ctx context.Context, id string, sampleWhPerToken float64, alpha float64, at time.Time) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateMappingEnergyEWMA")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateMappingEnergyEWMA(ctx, id, sampleWhPerToken, alpha, at)
}

func (_d *RoutingStoreWithTracing) UpdateMappingOpportunisticMetrics(ctx context.Context, id string, genSample float64, promptSample float64, alpha float64, at time.Time) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateMappingOpportunisticMetrics")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateMappingOpportunisticMetrics(ctx, id, genSample, promptSample, alpha, at)
}

func (_d *RoutingStoreWithTracing) UpdateMappingVisionCapable(ctx context.Context, id string, capable bool, at time.Time) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateMappingVisionCapable")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateMappingVisionCapable(ctx, id, capable, at)
}

func (_d *RoutingStoreWithTracing) UpdateModelGroup(ctx context.Context, group _sourceRouting.ModelGroup) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateModelGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateModelGroup(ctx, group)
}

func (_d *RoutingStoreWithTracing) UpdateResourceGroup(ctx context.Context, rg _sourceRouting.ResourceGroup) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateResourceGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateResourceGroup(ctx, rg)
}

func (_d *RoutingStoreWithTracing) UpdateResourceGroupSystemGroup(ctx context.Context, rgID string, systemGroupID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateResourceGroupSystemGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateResourceGroupSystemGroup(ctx, rgID, systemGroupID)
}

func (_d *RoutingStoreWithTracing) UpdateRuntimeSpecGPUMeasured(ctx context.Context, specID string, gpuIndex int, measuredMB int) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateRuntimeSpecGPUMeasured")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateRuntimeSpecGPUMeasured(ctx, specID, gpuIndex, measuredMB)
}

func (_d *RoutingStoreWithTracing) UpdateServerCertificateOverride(ctx context.Context, id string, override string) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateServerCertificateOverride")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateServerCertificateOverride(ctx, id, override)
}

func (_d *RoutingStoreWithTracing) UpdateServerEnergyConfig(ctx context.Context, id string, estimatedWatts float64, idleWatts float64, pricePerKwh float64, pue float64, priceUnit string) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateServerEnergyConfig")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateServerEnergyConfig(ctx, id, estimatedWatts, idleWatts, pricePerKwh, pue, priceUnit)
}

func (_d *RoutingStoreWithTracing) UpdateServerHTTPSSwitchOverride(ctx context.Context, id string, override string) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateServerHTTPSSwitchOverride")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateServerHTTPSSwitchOverride(ctx, id, override)
}

func (_d *RoutingStoreWithTracing) UpdateServerNetbirdAllowPing(ctx context.Context, id string, allow bool) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateServerNetbirdAllowPing")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateServerNetbirdAllowPing(ctx, id, allow)
}

func (_d *RoutingStoreWithTracing) UpdateServerNetbirdGroups(ctx context.Context, id string, groupsJSON string) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateServerNetbirdGroups")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateServerNetbirdGroups(ctx, id, groupsJSON)
}

func (_d *RoutingStoreWithTracing) UpdateServerNetbirdKey(ctx context.Context, id string, enabled bool, setupKeyID string, groupID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateServerNetbirdKey")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateServerNetbirdKey(ctx, id, enabled, setupKeyID, groupID)
}

func (_d *RoutingStoreWithTracing) UpdateServerNetbirdLink(ctx context.Context, id string, enabled bool, peerID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateServerNetbirdLink")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateServerNetbirdLink(ctx, id, enabled, peerID)
}

func (_d *RoutingStoreWithTracing) UpdateServerNetbirdPeerManaged(ctx context.Context, id string, managed bool) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateServerNetbirdPeerManaged")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateServerNetbirdPeerManaged(ctx, id, managed)
}

func (_d *RoutingStoreWithTracing) UpdateServerNetbirdPingExclude(ctx context.Context, id string, exclude bool) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateServerNetbirdPingExclude")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateServerNetbirdPingExclude(ctx, id, exclude)
}

func (_d *RoutingStoreWithTracing) UpdateServerNetbirdPolicyOverride(ctx context.Context, id string, override string) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateServerNetbirdPolicyOverride")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateServerNetbirdPolicyOverride(ctx, id, override)
}

func (_d *RoutingStoreWithTracing) UpdateServerNetbirdState(ctx context.Context, id string, domain string, peerID string, connected bool) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateServerNetbirdState")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateServerNetbirdState(ctx, id, domain, peerID, connected)
}

func (_d *RoutingStoreWithTracing) UpdateServerSystemGroup(ctx context.Context, serverID string, systemGroupID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateServerSystemGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateServerSystemGroup(ctx, serverID, systemGroupID)
}

func (_d *RoutingStoreWithTracing) UpdateService(ctx context.Context, svc _sourceRouting.Service) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateService")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateService(ctx, svc)
}

func (_d *RoutingStoreWithTracing) UpdateServiceSystemGroup(ctx context.Context, serviceID string, systemGroupID string) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpdateServiceSystemGroup")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpdateServiceSystemGroup(ctx, serviceID, systemGroupID)
}

func (_d *RoutingStoreWithTracing) UpsertAffinity(ctx context.Context, affinity _sourceRouting.RouteAffinity) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpsertAffinity")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpsertAffinity(ctx, affinity)
}

func (_d *RoutingStoreWithTracing) UpsertAgentToken(ctx context.Context, token _sourceRouting.AgentToken, secretHash string) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpsertAgentToken")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpsertAgentToken(ctx, token, secretHash)
}

func (_d *RoutingStoreWithTracing) UpsertCertificate(ctx context.Context, cert _sourceRouting.Certificate) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpsertCertificate")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpsertCertificate(ctx, cert)
}

func (_d *RoutingStoreWithTracing) UpsertModelSetting(ctx context.Context, setting _sourceRouting.ModelSetting) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpsertModelSetting")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpsertModelSetting(ctx, setting)
}

func (_d *RoutingStoreWithTracing) UpsertRuntimeSpec(ctx context.Context, spec _sourceRouting.RuntimeSpec) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpsertRuntimeSpec")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpsertRuntimeSpec(ctx, spec)
}

func (_d *RoutingStoreWithTracing) UpsertServerHardware(ctx context.Context, hardware _sourceRouting.ServerHardware) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpsertServerHardware")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpsertServerHardware(ctx, hardware)
}

func (_d *RoutingStoreWithTracing) UpsertTelemetry(ctx context.Context, telemetry _sourceRouting.ServerTelemetry) (err error) {
	ctx, span := Start(ctx, "routing.Store.UpsertTelemetry")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UpsertTelemetry(ctx, telemetry)
}

func (_d *RoutingStoreWithTracing) UsageAggregateSince(ctx context.Context, principalType string, principalID string, since time.Time) (requests int64, tokens int64, cost float64, err error) {
	ctx, span := Start(ctx, "routing.Store.UsageAggregateSince")
	defer span.End()
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
	}()
	return _d.Store.UsageAggregateSince(ctx, principalType, principalID, since)
}
