#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 OnPrem AI Gateway contributors
#
# Regenerate THIRD-PARTY-NOTICES.md from the actual dependency graphs.
#
# Go modules (backend + agent): github.com/google/go-licenses, run across several
#   GOOS values so platform-specific deps (Windows/plan9/aix) are included, then
#   unioned. Install once with:  go install github.com/google/go-licenses@latest
# Frontend (npm): license-checker, via `npx --yes license-checker`.
#
# The project's own modules (op-ai-gateway, op-ai-server-agent,
# op-ai-gateway-portal) are filtered out — they are the AGPL-3.0 work itself, not
# third-party. If any AGPL-INCOMPATIBLE license shows up (GPL-2.0-only, SSPL,
# BSL/proprietary), this script flags it on stderr; review before shipping.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/THIRD-PARTY-NOTICES.md"
export PATH="$PATH:$(go env GOPATH)/bin"

# CSV (module,url,license) -> markdown table rows, sorted & de-duplicated by
# module, with our own modules removed. mathutil is relabeled: go-licenses can't
# classify its cznic BSD-3-Clause LICENSE from the module path.
csv_to_rows() {
  sed 's#^modernc.org/mathutil,Unknown,Unknown#modernc.org/mathutil,https://gitlab.com/cznic/mathutil/-/blob/master/LICENSE,BSD-3-Clause#' \
    | grep -vE '^(op-ai-gateway|op-ai-server-agent),' \
    | sort -u -t, -k1,1 \
    | awk -F, 'NF>=3 {url=$2; lic=$3; printf "| `%s` | %s | %s |\n", $1, lic, (url=="Unknown"?"—":url)}'
}

go_licenses_multi() {
  local dir="$1" target="$2"; shift 2
  ( cd "$dir"
    for os in "$@"; do
      GOOS="$os" go-licenses csv "$target" 2>/dev/null || true
    done
  )
}

{
  echo "<!-- Generated by scripts/gen-third-party-notices.sh — do not edit by hand. -->"
  echo "# Third-Party Notices"
  echo
  echo "OP AI Gateway (\`AGPL-3.0-only\`) bundles third-party components under their"
  echo "own licenses, listed below. This file is generated; regenerate it with"
  echo "\`scripts/gen-third-party-notices.sh\`. The project's own modules are omitted."
  echo
  echo "## Backend (Go module \`op-ai-gateway\`)"
  echo
  echo "| Module | License | Source |"
  echo "|--------|---------|--------|"
  go_licenses_multi "$ROOT/gateway/backend" "./cmd/gateway" linux darwin windows | csv_to_rows
  echo
  echo "## Server-Agent (Go module \`op-ai-server-agent\`)"
  echo
  echo "| Module | License | Source |"
  echo "|--------|---------|--------|"
  go_licenses_multi "$ROOT/server-agent" "." linux darwin windows plan9 aix | csv_to_rows
  echo
  echo "## Frontend (npm package \`op-ai-gateway-portal\`)"
  echo
  echo "Production dependencies (dev-only tooling such as Vite/Vitest/TypeScript is"
  echo "excluded — it is not shipped to browsers):"
  echo
  echo "| Package | License |"
  echo "|---------|---------|"
  ( cd "$ROOT/gateway/frontend"
    npx --yes license-checker --production --csv --columns name,licenses 2>/dev/null \
      | tail -n +2 \
      | tr -d '"' \
      | grep -vE '^op-ai-gateway-portal' \
      | sort -u \
      | awk -F, 'NF>=2 {printf "| `%s` | %s |\n", $1, $2}'
  )
} > "$OUT"

# Flag AGPL-incompatible licenses (best-effort).
if grep -iEn 'GPL-2\.0-only|SSPL|Business Source|BUSL|proprietary|UNLICENSED' "$OUT" >/dev/null; then
  echo "WARNING: possible AGPL-incompatible license in $OUT — review:" >&2
  grep -iEn 'GPL-2\.0-only|SSPL|Business Source|BUSL|proprietary|UNLICENSED' "$OUT" >&2
fi

echo "wrote $OUT"
